edgexfoundry/edgex-docs

Dockerfile.build
build.sh

This PR refactors the two following things:
1. `Dockerfile.build` - now uses the base image: `nexus3.edgexfoundry.org:10003/edgex-docs-builder:latest` in the `FROM` statement. This base image has all the dependencies need to build all the documentation. This should speed up the Jenkins builds on the significantly. I also attempted to minimize the number of layers in the builder image as much as I could.
2. `build.sh`-  now accepts an argument for the "stream". This allows ties into what RAML files are pulled from github.com. You can see that on line #25. The default "stream" is master, so if you wanted to build the `edinburgh` stream, you would run:
```
$ ./build.sh edinburgh
```

refactor Dockerfile to use new base image with dependencies

---

examples/Ch-ExamplesAddingModbusDevice.rst
getting-started/Ch-GettingStartedUsers.rst
quick-start/Ch-QuickStart.rst
security/Ch-APIGateway.rst
security/Ch-SecretStore.rst
walk-through/Ch-WalkthroughRunning.rst

Replace references to the delhi docker-compose file with references to the edinburgh docker-compose file.

Replace references to the delhi docker-compose with edinburgh

---

walk-through/Ch-WalkthroughProvision.rst

In API walk through, replaced addressable with protocols in device
creation call.  Example did not have a protocols field and result of
POST was a _no supporting protocol specified for device_ result.
https://github.com/edgexfoundry/edgex-docs/issues/8
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>

Replace Addressable With Protocols

---

api/Ch-APISupportingServicesScheduling.rst

Fix #16
Updating Scheduler documentation for the Edinburgh release.
Removed references to Addressable, Schedule, and Schedule Event.
Added references Interval, and IntervalAction.
Updated example curl commands to reflect inclusion of the Interval and IntervalAction types.
Signed-off-by: xmlviking <ecotter@gmail.com>

Updating Edinburgh Scheduler API docs

---

examples/Ch-ExamplesAddingMQTTDevice.rst
examples/Ch-ExamplesAddingModbusDevice.rst
examples/Ch-ExamplesAddingSNMPDevice.rst
getting-started/Ch-GettingStartedUsers.rst
getting-started/Ch-GettingStartedUsersNexus.rst
quick-start/Ch-QuickStart.rst
security/Ch-APIGateway.rst
security/Ch-SecretStore.rst
walk-through/Ch-WalkthroughRunning.rst

https://github.com/edgexfoundry/developer-scripts/issues/128
restructured the edgexfoundry/developer-scripts /compose-files directory
into a /releases directory with release-specific subdirectories.
This commit updates the related website documentation references.
https://github.com/edgexfoundry/edgex-docs/issues/11
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>

Update Docker Compose-file Locations

---

api/Ch-APISupportingServicesScheduling.rst

Updated Ch-APISupportingServicesScheduler.rst
Removed references to the addressable type.
Removed references to the schedule type.
Removed references to the schedule event type.
Added example(s) using the new interval and interval action types.
Signed-off-by: xmlviking <ecotter@gmail.com>

Updating API Scheduler documentation

---

security/Ch-SecretStore.rst
security/token-file-provider.1.rst

The file-token-provider is a new Fuji utility for generating
per-service Vault tokens that will be spawned from
securitys-secretstore-setup to pre-create tokens.
The existince of file-token-provider does not preclude the
creation of other token providers in the future.

RST-formatted man page for file-token-provider.

---

security/Ch-SecretStore.rst
security/security-secrets-setup.1.rst

security-secrets-setup is a new Fuji utility that enhances
the pkisetup utility from Edinburgh with explicit capabilities
to create, create and cache, or import a PKI and deploy it
on-device.  It also replaces some amount of wrapper logic
previously written in shell script by providing the higher
level abstraction.
security-secrets-setup is a critical component for the
secret management hardening being done in Fuji release.
The included man-style page documents the externally-visible
functionality of security-secrets-setup.

RST-formatted man page for security-secrets-setup.

---

security/Ch-SecretStore.rst
security/security-file-token-provider.1.rst

Deltas:
- Rename to security-file-token-provider
- Change edgex-use-defaults to edgex_use_defaults
to follow normal JS conventions
- custom_policy is JSON object instead of array of objects
to bring in line with JSON serialization format of HCL
- Updated docs to reflect how display_name is tweaked by Vault
- Added metadata to reflect service name as created by utility
to be used by go-mod-secrets client as a URL hint

Post-implementation man page update for security-file-token-provider.

---

security/security-secrets-setup.1.rst

Corrects error in the filenames of hard-coded JSON files.
Fixes #44
edgex-kong.json --> pkisetup-kong.json
edgex-vault.json --> pkisetup-vault.json
Also fix description of directory naming rules
that do not apply in the current release.

Corrects error in the filenames of hard-coded JSON files.

---

security/security-secrets-setup.1.rst

Corrects error in the filenames of hard-coded JSON files.
Fixes #44 on FUJI branch of documentation
edgex-kong.json --> pkisetup-kong.json
edgex-vault.json --> pkisetup-vault.json
Also fix description of directory naming rules
that do not apply in the current release.
Signed-off-by: Bryon Nevis bryon.nevis@intel.com

FUJI BRANCH: Corrects error in the filenames of hard-coded JSON files.

---

design/adr/0001-Registy-Refactor.md

We are now keeping the Boolean  -r/-registry command line flag and NOT adding the `Enabled` field to the RegistryInfo struct. 
ADR updated to reflect these changes.
closes #81

doc(ADR): Update Registry Refactoring ADR for chnages to keep -r/-registry

---

Jenkinsfile

This PR fixes the current build issue after mkdocs-material release their 5.x version. A follow-on PR will be created to address the upgrade to mkdocs-material 5.x.
https://squidfunk.github.io/mkdocs-material/releases/5/#how-to-upgrade
Issue Number:

Pin mkdocs-material to 4.6.3 and add recheck trigger

---

docs_src/microservices/security/Ch-SecretStore.md

The link is broken 
Issue Number:
The broken link :P

docs: fix a broken docker-compose link

---

docs_src/microservices/device/Ch-DeviceServices.md

fix https://github.com/edgexfoundry/edgex-docs/issues/161
- modify the requirement document URL
- remove the section of sequence diagram
Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>
Issue Number: #161

Correct the document links in Device Service page

---

docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
docs_src/examples/Ch-ExamplesAddingModbusDevice.md
docs_src/microservices/security/Ch-SecretStore.md
docs_src/walk-through/Ch-WalkthroughRunning.md

Fixes: #187
Update documentation containing docker-compose file references from `Fuji` to `Geneva`
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
Issue Number: #187 
- Change/update the documentation that has docker-compose references from release `Fuji` to release `Geneva`.

Update docker-compose references to release Geneva

---

docs_src/microservices/application/AppServiceConfigurable.md

Issue Number: #232
All links from App Service Configuration's available functions now go to the appropriate location in the SDK built-in functions documentation.

fix: Fix links from App Service Config functions to SDK details for the functions

---

docs_src/getting-started/Ch-GettingStartedGoDevelopers.md

modified Go Developers guide to indicate project now uses Go 1.15
Fixes: #228
n/a - updated docs to indicate project uses Go 1.15
Issue Number: #228 
Ch-GettingStartedGoDevelopers.md

build: upgrade docs to reference use of Go 1.15

---

docs_src/general/ServiceConfiguration.md
docs_src/microservices/application/GeneralAppServiceConfig.md
docs_src/microservices/core/command/Ch-Command.md
docs_src/microservices/core/data/Ch-CoreData.md
docs_src/microservices/core/metadata/Ch-Metadata.md
docs_src/microservices/device/Ch-DeviceServices.md
docs_src/microservices/device/virtual/Ch-VirtualDevice.md
docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
docs_src/microservices/support/scheduler/Ch-Scheduling.md
docs_src/microservices/system-management/agent/Ch_SysMgmtAgent.md

fix links to point to common configuration properties and not just common configuration
fix #250
none
Issue Number:
#250 
change links from Ch-Configuration.md#configuration to Ch-Configuration.md#configuration-properties where applicable

fix(microservices): fix all the links to common configuration

---

mkdocs.yml
versions.json

This will add a new version for Hanoi and will update mkdocs to generate site contents to a new folder.
Missing step not going to be done in this PR is to make 1.3 the default version when navigating to docs.edgexfoundry.org. That is done by updating this line: https://github.com/edgexfoundry/edgex-docs/blob/gh-pages/index.html#L6
Issue Number:

build: add Hanoi version 1.3

---

docs_src/microservices/device/virtual/Ch-VirtualDevice.md

Issue Number: fix #248 
The following array value types are added into the introduction section:
- BoolArray
- Int8Array, Int16Array, Int32Array, Int64Array
- Uint8Array, Uint16Array, Uint32Array, Uint64Array
- Float32Array, Float64Array
On hold till [device-virtual-go PR#133](https://github.com/edgexfoundry/device-virtual-go/pull/133) is merged.

feat(VirtualDeviceService): Add supported array value types

---

docs_src/design/legacy-design/device-service/discovery.md

Provision Watcher operation for devices which may be addressed via multiple Protocol schemes was unclear. This was highlighted in https://github.com/edgexfoundry/device-sdk-go/issues/598
Added paragraph indicating that each Protocol is to be evaluated separately

fix(legacy): clarify provision watcher matching for multiple protocols

---

docs_src/design/adr/system-management/001-docker-image-guidelines.md

ADR: Docker container guidelines
close #206
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
New ADR for docker security guidelines
Current docker container deployments lack updated security guidelines
Issue Number: 206

feat(adr): Docker container guidelines

---

docs_src/microservices/application/AdvancedTopics.md
docs_src/microservices/configuration/Ch-Configuration.md

old value was 30 seconds
fixes: #267
#267 

fix(ref): change default startup duration to 60 seconds

---

docs_src/design/TOC.md
docs_src/design/adr/security/0015-in-cluster-tls.md

This ADR makes the case that EdgeX should not use TLS
to secure on-box communication.
Fixes #284 
Fixes https://github.com/edgexfoundry/edgex-go/issues/1925 (willnotfix if approved)
Fixes https://github.com/edgexfoundry/edgex-go/issues/1942 (willnotifx if approved)
Fixes https://github.com/edgexfoundry/edgex-go/issues/1941 (willnotfix if approved)
Fixes https://github.com/edgexfoundry/edgex-go/issues/2454 (willnotfix if approved)
Fixes …

feat(adr): ADR for detailing when TLS is or is not used

---

docs_src/design/adr/core/0003-V2-API-Principles.md
docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
docs_src/examples/Ch-ExamplesAddingModbusDevice.md
docs_src/getting-started/Ch-GettingStartedSDK-C.md
docs_src/getting-started/Ch-GettingStartedSDK-Go.md
docs_src/getting-started/Ch-GettingStartedUsers.md
docs_src/getting-started/quick-start/index.md
docs_src/index.md
docs_src/microservices/core/database/Ch-Redis.md
docs_src/microservices/security/Ch-Docker-Swarm-SecuringDeviceServices.md
docs_src/microservices/security/Ch-SecretStore.md
mkdocs.yml

fixes:#293
changed references to Geneva compose files where it was easy to do
changed any place where Geneva was referenced as the latest release
made note where Geneva is used in examples that later releases do exist
added Redis guidance to core services (from the Wiki)
updated release cadence and future release names
n/a
#293 
clean up of Geneva references to provide better clarity in the docs

fix(ref): clean up all geneva specific references for hanoi

---

docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md

fix #331 
The V2 of operating state has been decided to use value range UP/DOWN/UNKNOWN; however, https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md#device-states is still using value range ENABLED/DISABLED, which needs to be updated.

fix(adr): Update device service V2 API documentation for the value range of operating state

---

docs_src/getting-started/Ch-GettingStartedUsers.md

Directions reference 1.3.0 tag
Directions now reference the `hanoi` branch

fix: Adjust the Hanoi custom compose build directions

---

docs_src/design/adr/device-service/0002-Array-Datatypes.md

Removed the implementation for v2 API changes on array of strings and non-array types that was overruled by architect's meeting in January.
Decision was made to keep implementation as it is in v1
Takes out suggestion that there will be a change in Readings for arrays for V2.  This was reversed in the Jan 2021 Architect's meeting

fix(adr): updated 0002 to remove proposed V2 API changes

---

docs_src/getting-started/Ch-GettingStartedUsers.md

Custom compose section has example using `mqtt` option
Custom compose section example now uses `mqtt-bus` option

fix: Hanoi - Change Compose Builder mqtt option to mqtt-bus

---

docs_src/design/legacy-design/device-service/discovery.md

Use of noninclusive terminology
Removed blacklist/whitelist reference

fix(legacy): Remove noninclusive language from device discovery spec

---

docs_src/getting-started/Ch-GettingStartedUsers.md

README link is to the `1.3.0 tag` 
README link is to the `hanoi branch` 

fix: Hanoi: Update link to Compose Builder README to be from the `hanoi` branch

---

docs_src/api/supporting/Ch-APISupportingServicesScheduling.md
docs_src/microservices/support/scheduler/Ch-Scheduling.md

frequency does not abide by the ISO 8601 standard
error in docs suggesting interval frequency abides by ISO standard

fix(microservices): fix description of frequency for scheduler interval

---

docs_src/index.md

Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
- [x ] Changes have been rendered and validated locally using mkdocs-material (see edgex-docs README)
- [x ] Docs have been added / updated (for bug fixes / features)
The list of SDKs contains twice the Golang Device SDK.
The list only contains the Golang Device SDK once and lists the Golang Application SDK.
None

fix: Correct list of SDKs in Introduction

---

docs_src/microservices/application/BuiltIn.md

App SDK Built-in functions doc not current for Ireland
App SDK Built-in functions doc now current for Ireland

feat: Update Built-in functions documentation for Ireland

---

docs/index.html

Default to 1.3 docs
Now defaults to 2.0 docs

build: Change the default docs landing page to be 2.0

---

docs_src/microservices/application/V2Migration.md

No section in App Services Migration Guide for dealing with V2 dependencies
New section added to App Services Migration Guide for dealing with V2 dependencies

feat: Add dependencies section to App Service migration guide

---

docs_src/design/adr/013-Device-Service-Events-Message-Bus.md
docs_src/design/adr/014-Secret-Provider-For-All.md
docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
docs_src/examples/Ch-ExamplesAddingModbusDevice.md
docs_src/microservices/application/AdvancedTopics.md
docs_src/microservices/application/AppServiceConfigurable.md
docs_src/microservices/application/Triggers.md
docs_src/microservices/configuration/CommonEnvironmentVariables.md
docs_src/microservices/device/V2Migration.md
docs_src/security/Ch-Configuring-Add-On-Services.md
docs_src/security/security-file-token-provider.1.md

TOML examples have single quotes or mix of single and double quotes
TOML examples now have just double quotes
Also update some examples to have proper tags like `toml`, `yaml`, etc

fix: Clean up TOML examples to have only double quotes

---

docs_src/getting-started/Ch-GettingStartedSnapUsers.md

Signed-off-by: Tony Espy <espy@canonical.com>
- [_see below_] Changes have been rendered and validated locally using mkdocs-material (see edgex-docs README)
- [NA] Docs have been added / updated (for bug fixes / features)
**Note** - the instructions in the README.md did not work for me. I was able install python3-pip, and then pip installed mkdocs and mkdocs-material (although the instructions specify a very old version), however when I tried running `mkdocs serve`, I got "command not found".
Also the PR template should probably the …

feat: update snap getting started for V2

---

docs_src/getting-started/Ch-GettingStartedSDK-C.md

Guide for C device SDK contains a core-data URL which is not correctly changed for the v2 API
corrected URL

fix: fixed incorrect URL for core-data query

---

docs_src/getting-started/Ch-GettingStartedCDevelopers.md
docs_src/getting-started/Ch-GettingStartedSDK-C.md

Discussion of C SDK dependencies refers to Ubuntu without specifying a version
- Ubuntu specified as the 20.04 LTS release
- Added note on dependencies of dependencies
- Removed inconsistent use of `apt` and `apt-get`
- Added note on returning reading values

fix: small clarifications for device-sdk-c (#558)

---

docs_src/microservices/configuration/CommonConfiguration.md

Common SecretStore config was out-of-date for V2. It is now up-to-date

feat: Update common SecretStore config for V2

---

docs_src/getting-started/Ch-GettingStartedCDevelopers.md

Command suggested for installing the supporting libraries needed by the C SDK does not work
Specified a working command for current Debian. Noted the lack of required MQTT package in the latest Ubuntu LTS and documented how to install IOTech's build of it.

fix: dependency installation for C development

---

mkdocs.yml
versions.json

Default drop down will still be 2.0-Ireland.
2.1-Jakarta will now be in the drop down and any merges into `main` will show up there.

build: Switch to Jakarta for documentation development

---

docs_src/microservices/configuration/CommonConfiguration.md
docs_src/security/SeedingServiceSecrets.md
mkdocs.yml

closes #586
related to https://github.com/edgexfoundry/edgex-docs/pull/587

feat: Document new Seeding Service Secrets capability

---

docs_src/design/TOC.md
docs_src/design/adr/core/0019-EdgeX-CLI-V2.md

add edgex-cli V2 ADR
This PR adds a new  ADR with a technical plan for creation of a 2.0 version of edgex-cli which supports the new V2 REST APIs.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
ADR with a technical plan for edgex-cli 2.0.

feat: Add EdgeX-CLI-V2 ADR

---

docs_src/microservices/core/metadata/Ch-Metadata.md

Change Notifications.PostDeviceChanges default value to false, and
correct to Notifications related config default value to meet the
current v2 design on Core Metadata page.
Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>

fix(microservices): Correct metadata default config

---

docs_src/microservices/application/AppServiceConfigurable.md
docs_src/microservices/application/BuiltIn.md

Add documentation for new AESProtection transform and deprecate legacy
Encryption transform.

feat(microservices): Document New AESProtection Transform

---

docs_src/microservices/core/data/Ch-CoreData.md
docs_src/microservices/device/Ch-DeviceServices.md

feat: Document Device Service Publish to MessageBus default capability

---

docs_src/microservices/application/BuiltIn.md

Cherry-pick https://github.com/edgexfoundry/edgex-docs/commit/90c88562df12ae5405ad162d713904bd6b63ad63 into main.

fix: Update link to post-release security advisory.

---

docs_src/security/Ch-APIGateway.md

fix: Pass Kong admin JWT to secrets-config utility (ireland)

---

docs_src/assets/javascripts/version-select.js

Related to #678
I believe this fixes the version switch only for version 2.2, when switching to any other version, but not vice versa.
Additional PRs would have to backport this fix into [gh-pages](https://github.com/edgexfoundry/edgex-docs/tree/gh-pages). I guess the CI populates `2.2, 2.1, ...` directories of gh-pages from `main, jakarta, ...` branches? 
To validate that it works, I've tested it locally by switching to gh-pages branch and adding this fix in 2.1 and 2.2 directories. I've then served the files with a python http server:
```
python3 -m http.server
```
See the video below; note the swagger URL version change in the inspection area. …

fix: stay on page after version switch

---

docs_src/assets/javascripts/version-select.js
versions.json

Same as #679 but for Ireland.
Related to #678
This fixes the version switch from version 2.0 to others, but not vice versa.
It also removes the obsolete versions list from this branch; see #680

fix: stay on page after version switch (ireland)

---

docs_src/microservices/device/virtual/Ch-VirtualDevice.md

Issue [#260](https://github.com/edgexfoundry/device-virtual-go/issues/260) in device-virtual-go removes the ql library from the
microservice. Remove mention in docs.
Signed-off-by: Corey Mutter <CoreyMutter@eaton.com>

fix(microservices): device-virtual no longer using ql

---

README.md

This is so it doesn't conflict with Kong when it is running.

fix: Adjust port number for mkdocs-material in README

---

docs_src/getting-started/tools/Ch-CommandLineInterface.md

This commit updates the edgex-cli getting-started documentation with information about the new V2 edgex-cli.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

fix: update CLI V2 documentation

---

README.md
versions.json

build: Expand versioning process in readme

---

.gitignore
Dockerfile.docs
Jenkinsfile
Makefile
README.md
mkdocs.yml

- Add Makfile to build & server docs
- Add Dockerfile.docs to serve as the mkdocs image used for building docs
- Add documentation in README on how to use make commands

build: add Makefile and docker image

---

docs_src/assets/stylesheets/branding.css
docs_src/assets/stylesheets/links.css
mkdocs.yml

In response to #655, PR #691 changed the link colors to brighter shades of purple and red. That change made the links in body inconsistent with links in the sidebar and ToC.
This PR tries to make the links readable and at the same time stay consistent with other links (sidebar, toc) and the color family. The selected link colors are from the EdgeX color family, identical to the red and purple of the logo, as intended originally. I only swapped the primary and accent colors. I also had to override the header color to be same as the accent (now purple) instead of primary (now red).
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: …

fix(ref): make link colors consistent

---

docs_src/examples/index.md

point to `deployment/helm` instead of `deployment/kubernetes`
addresses and closes #720 for `jakarta` branch
Signed-off-by: Shantanoo 'Shan' Desai <shantanoo.desai@gmail.com>

fix: point to correct link for kubernetes example

---

docs_src/getting-started/index.md

feat: address supported architectures in Getting Started

---

docs_src/getting-started/Ch-GettingStartedSnapUsers.md

This PR updates the Getting Started with Snap guide for the jakarta docs:
* replaces the content with links to readmes 
* updates the introduction

fix: Replace Getting Started with Snaps content with README refs (jakarta)

---

docs_src/general/PlatformRequirements.md
docs_src/getting-started/Ch-GettingStartedDevelopers.md
docs_src/getting-started/index.md

PR https://github.com/edgexfoundry/edgex-docs/pull/744 added the description of supported architectures. The text has some overlapping information with the platform requirement page. I've moved the information to the platforms requirements page and linked to it. Also fixed another hyperlink to that page.
Other resolved issues:
- It claimed that ZMQ doesn't compile on arm32, which isn't accurate. Compiling ZMQ for arm32 is possible; cross-compiling it is difficult.
- A blanket statement that artifacts are released only for amd64 and arm64 is limiting. In some cases, we may want to release some services for other architectures. For example, the [device-gpio snap](https://snapcraft.io/edgex-device-gpio) is built also for armhf to allow installation on a wider range of devices.
Related to …

fix: re-organize the description of supported architectures

---

docs_src/general/ServicePorts.md

- Moved services to the right category, according to the architecture
- redis and consul to core
- rules engine to support
- SMA to support
- Corrected the device-rfid-llrp name
- Added port 4000 for the UI
- Squashed Kong ports into 1 row

fix: cleanup default service ports

---

docs_src/api/applications/Ch-APIAppFunctionsSDK.md
docs_src/api/core/Ch-APICoreCommand.md
docs_src/api/core/Ch-APICoreData.md
docs_src/api/core/Ch-APICoreMetadata.md
docs_src/api/devices/Ch-APIDeviceSDK.md
docs_src/api/management/Ch-APISystemManagement.md
docs_src/api/support/Ch-APISupportNotifications.md
docs_src/api/support/Ch-APISupportScheduler.md

This PR updates the swagger links to the next release version: 2.3.0

ci: automated Swagger API version changes: 2.2.0 --> 2.3.0

---

mkdocs.yml

Update Google Analytics configuration based on the latest found mkdocs documentation here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#configuration
I verified that the Google Analytics snippet is now in the generated HTML
```html
...
<script>function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","G-38531ZZHBN"),document.addEventListener("DOMContentLoaded",function(){document.forms.search&&document.forms.search.query.addEventListener("blur",function(){this.value&&gtag("event","search",{search_term:this.value})}),"undefined"!=typeof location$&&location$.subscribe(function(e){gtag("config","G-38531ZZHBN",{page_path:e.pathname})})})</script>
<script async …
```

fix: update google analytics config per latest documentation

---

docs_src/examples/index.md
docs_src/microservices/support/eKuiper/Ch-eKuiper.md
mkdocs.yml

* Enable mkdocs htmlproofer plugin and integrate it with CI.
* Fix initial broken links in markdown.
* Ignore links to support.google.com - two links are failing to validate. Don't think htmlproofer plugin validation is very robust for redirects / certain header types
Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

ci: enable htmlproofer

---

Jenkinsfile
Makefile
README.md
mkdocs.yml

ci: only enable HTML proofer for Jenkins

---

docs_src/design/TOC.md
docs_src/design/adr/0024-system-events.md

feat: Create System Events ADR

---

docs_src/getting-started/tools/Ch-CommandLineInterface.md
mkdocs.yml

The CLI docs is broken because some command outputs include `{{` which is processed by the macros plugin as a template.
See https://docs.edgexfoundry.org/2.3/getting-started/tools/Ch-CommandLineInterface/
This PR escapes those instances and adds a build flag to throw build errors if this happens again, instead of showing the error on the page in browser.
References:
- https://jinja.palletsprojects.com/en/2.11.x/templates/?highlight=raw#escaping
- https://mkdocs-macros-plugin.readthedocs.io/en/latest/advanced/
It is important to make the build fail right away rather than later on in CI because the error doesn't tell which file the error comes from. It will be hard to understand if the error is produced too late after the addition of many files. Example error:
```
INFO     -  [macros] - …
```

fix: Escape unintended macro templates, fail docs build on errors

---

index.html
versions.json

The following PRs included the old version and index files which overrode the production copies: #819, #820

revert: hanoi/geneva version override by CI

---

docs/404.html
docs/index.html
docs/versions.json

This is a replica of https://github.com/edgexfoundry/edgex-docs/pull/813 to have the files on the main branch. The original PR added the changes directly to the gh-pages branch some of which were getting overridden by copies in main.

feat: Referencing doc pages with latest alias

---

docs_src/microservices/core/metadata/Ch-Metadata.md

feat: Document Core Metadata Device System Events

---

docs_src/getting-started/Ch-GettingStartedSnapUsers.md

This replaces the path to fetch the Consul management token, instead of the bootstrap token. Related to https://github.com/edgexfoundry/edgex-go/pull/4126
The snap doesn't have a wrapper makefile recipe / script to fetch the token, so a change similar to https://github.com/edgexfoundry/edgex-compose/pull/270 isn't needed.

fix: Change snap getting started to use consul management token

---

docs_src/microservices/device/Ch-DeviceServiceList.md

Related to #842
Also update Release and Version for existing and fixed links to point to proper repo tags
**_Note that this is for Kamakura. Similar PRs will be done for Jakarta and main one this PR is approved and merged._**

refactor: [Kamakura] Rework device service list and add new camera device services

---

docs_src/getting-started/Ch-GettingStartedDockerUsers.md

Docker seems to be actively updating their Compose documention, so the previous link
is no longer valid.

fix: Fix broken link to docker compose install

---

docs_src/examples/index.md
docs_src/getting-started/Ch-GettingStartedDockerUsers.md
docs_src/microservices/support/eKuiper/Ch-eKuiper.md

fixes: #778
all of these fixes are already in Levski/main branch
most of these issues are due to changes to source or 3rd party docs post Kamakura release

fix: correct broken links in Kamakura version of docs

---

docs_src/microservices/configuration/CommonEnvironmentVariables.md

feat: Document new "none" value for EDGEX_CONFIGURATION_PROVIDER

---

docs_src/security/Ch-RemoteDeviceServices.md

fix: Replace broken link for SHH Server in docker

---

docs_src/getting-started/Ch-GettingStartedSnapUsers.md

This PR updates the documentation as two deprecated apps kuiper and ASC will be removed from edgexfoundry snap since version 3.0. They are available as standalone snaps: [edgex-app-service-configurable snap](https://snapcraft.io/edgex-app-service-configurable) and [edegx-ekuiper snap](https://snapcraft.io/edgex-ekuiper).

feat!: Remove deprecated kuiper and ASC from edgexfoundry snap

---

docs_src/microservices/application/AppServiceConfigurable.md
docs_src/microservices/application/BuiltIn.md

fix: remove references to deprecated code for EncryptWithAES

---

docs_src/microservices/application/Triggers.md

fix: remove deprecated code for MessageProcessor

---

docs_src/getting-started/Ch-GettingStartedSnapUsers.md

Supporting documentation for:
- edgexfoundry: https://github.com/edgexfoundry/edgex-go/pull/4277
- edgex-ekuiper: https://github.com/canonical/edgex-ekuiper-snap/pull/44
- edgex-ui: https://github.com/edgexfoundry/edgex-ui-go/pull/587
- edgex-device-modbus: https://github.com/edgexfoundry/device-modbus-go/pull/400
- edgex-device-snmp: https://github.com/edgexfoundry/device-snmp-go/pull/213
- edgex-device-rest: https://github.com/edgexfoundry/device-rest-go/pull/238
- edgex-device-mqtt: https://github.com/edgexfoundry/device-mqtt-go/pull/454
- edgex-device-gpio: https://github.com/edgexfoundry/device-gpio/pull/79
- edgex-device-rfid-llrp: https://github.com/edgexfoundry/device-rfid-llrp-go/pull/134
- edgex-device-usb-camera: https://github.com/edgexfoundry/device-usb-camera/pull/129
- …

feat: Update snap docs for v3 configuration changes

---

docs_src/design/TOC.md
docs_src/design/ucr/URIs-for-Files.md

feat: Create UCR for using URIs to load files

---

mkdocs.yml

feat: update mkdocs to have sitemap use docs URLs vs github URLs

---

docs_src/design/adr/0023-North-South-Messaging.md
docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md
docs_src/microservices/core/command/Ch-Command.md

docs: Update docs to use true/false for ds-pushevent and ds-returnevent in 3.0

---

docs_src/microservices/application/AppFunctionContextAPI.md
docs_src/microservices/application/AppServiceConfigurable.md
docs_src/microservices/application/BuiltIn.md

fix: remove deprecated PushToCore references

---

Dockerfile.docs
Makefile
README.md

Kong's uses port 8001 for the admin API. So, if running the services natively or in snaps, `make serve` fails with error:
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint eloquent_yonath (b91243329ae1088fa44762975cc9ad7944d7bbf9ecfcd30b6753fca3212c10ea): Error starting userland proxy: listen tcp4 0.0.0.0:8001: bind: address already in use.
```
```
$ sudo lsof -nPi :8001
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nginx   19104 root   13u  IPv4 152911      0t0  TCP 127.0.0.1:8001 (LISTEN)
...
```
Moreover, the docs port is set to 8001 in the Docker port mapping, resulting in confusing instructions in the mkdocs logs:
```
$ make serve
...
INFO     -  [11:25:19] Watching paths for changes: 'docs_src', 'mkdocs.yml'
INFO     - …
```

fix: Change mkdocs and Docker port to 8008

---

docs_src/microservices/configuration/CommonCommandLineOptions.md

fix: Add missing default value for ConfigProvider command line flag

---

docs/robots.txt
mkdocs.yml

fix sitemap for main or MN release to have correct URL references

fix: change robots.txt to include all sitemaps and remove disallow

---

mkdocs.yml

fix: fix sitemap for Geneva release to have version in sitemap.xml

---

docs_src/getting-started/Ch-GettingStartedDTOValidation.md
mkdocs.yml

- Document the restriction was reduced for the command name and resource name, and usage of URL escape for API.
- Move this page to the Developers section
Close #979 #950

feat: Document the URL escape for device command name and resource name

---

docs_src/walk-through/Ch-WalkthroughProvision.md

Per https://github.com/edgexfoundry/edgex-go/pull/4375 and https://github.com/edgexfoundry/go-mod-core-contracts/pull/807, the notify field of Device DTO is removed, so that documentation should be updated to remove the notify field as well.

feat!: Remove Notify field out of Device DTO

---

docs_src/microservices/core/metadata/Ch-Metadata.md

Per https://github.com/edgexfoundry/go-mod-core-contracts/pull/803 and https://github.com/edgexfoundry/go-mod-core-contracts/pull/800, new fields `properties` are added into Device dto and ProvisionWatcher dto. This PR updates edgex-docs with the description of these new fields.
fixes #969

feat: Add description for new field properties of Device dto and ProvisionWatcher dto

---

docs_src/security/Ch-APIGateway.md

Recent changes to secrets-config tool

fix: Bring security docs up to do date

---

docs_src/microservices/configuration/CommonCommandLineOptions.md

feat: Document new -d/--dev command-line flag

---

docs_src/security/Ch-DelayedStartServices.md

feat(security): Add custom spire config env variable

---

docs_src/security/Ch-SecretProviderApi.md

- Change path to secretName
- Rename RegisteredSecretUpdatedCallback to RegisterSecretUpdatedCallback
- Add notes on wildcard usage
https://github.com/edgexfoundry/go-mod-bootstrap/pull/522

docs: update SecretProviderAPI (go-mod-bootstrap/522)

---

README.md

Although some systems accept [0.0.0.0](https://en.wikipedia.org/wiki/0.0.0.0) as the destination address for the loopback (127.0.0.1 or localhost), it is strange and looks like a mistake.

fix: Use localhost for browsing locally served docs

---

docs_src/design/Process.md
docs_src/design/adr/template.md
docs_src/design/ucr/template.md

Making some of the improvements discussed in the Minnesota planning:
- Replace template URLs with references to source to avoid confusion when looking at the rendered view which has no section explanations ([example](https://docs.edgexfoundry.org/2.3/design/ucr/template/))
- Improve formatting of comments
- Fix heading levels consistency
- UCR Existing solutions: add EdgeX to make it clear that existing solutions may be using EdgeX in a non-standard way

style: Improve formatting of UCR and ADR templates

---

docs_src/getting-started/Ch-GettingStartedDockerUsers.md
docs_src/getting-started/quick-start/index.md
template_macros.yaml

We had an extensive discussion in https://github.com/edgexfoundry/edgex-docs/pull/1000 and working group calls which ended with keeping only the minor version and API version as macros. The release field was added again in https://github.com/edgexfoundry/edgex-docs/pull/1074 without any description.
This is confusing and unnecessary:
- The macro can be misused in Github URLs, leading to issues discussed in [#1000](https://github.com/edgexfoundry/edgex-docs/pull/1000#discussion_r1154378996)
- The uses for the added macro is misleading, telling the reader something is the "latest" release or version which ends up becoming invalid at the next release.
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: …

fix: Remove release macro (again)

---

docs_src/microservices/core/command/Ch-Command.md

fix: Rename ExternalMqtt.SecretPath to SecretName

---

docs_src/general/ServicePorts.md

fix: [kamakura] Correct published port number for Device GPIO

---

docs_src/examples/Ch-ExamplesAddingMQTTDevice.md

The example now it works for MQTT devices.
- [x ] Changes have been rendered and validated locally using mkdocs-material (see edgex-docs README)

fix: Pre-defined example for MQTT

---

Dockerfile.docs

fix: pin mkdocs to 1.4.3 to avoid compatability issues with plugins

---

docs_src/examples/Ch-ExamplesAddingModbusDevice.md

The example given for the modbus has the scale value as string, and it must be a number as it can be located in the given example in the modbus device service https://github.com/edgexfoundry/device-modbus-go/blob/main/cmd/res/profiles/modbus.test.device.profile.yml

fix: scale format integer format in modbus yml example

---

docs_src/examples/Ch-ExamplesAddingModbusDevice.md

The example given for the modbus has the scale value as string, and it must be a number as it can be located in the given example in the modbus device service https://github.com/edgexfoundry/device-modbus-go/blob/main/cmd/res/profiles/modbus.test.device.profile.yml

fix: scale format integer format in yml example

---

docs_src/microservices/general/index.md
docs_src/security/SeedingServiceSecrets.md

docs: Add general uri4files feature description

---

docs_src/microservices/configuration/CommonConfiguration.md

Add EnableNameFieldEscape config to allow name field escape configurable

docs: Add name field escape config

---

docs_src/microservices/device/Ch-DeviceServices.md

fixes #1230. Add LastConnected metric to device service common config.

feat: Add LastConnected metric to common config

---

docs_src/getting-started/native/Ch-BuildRunOnArm32.md
docs_src/getting-started/native/Ch-BuildRunOnLinuxDistro.md
docs_src/getting-started/native/Ch-BuildRunOnWindows.md

fix: [Napa] Add starting core-common-config-bootstrapper to run native guides

---

docs_src/getting-started/native/Ch-BuildRunOnArm32.md
docs_src/getting-started/native/Ch-BuildRunOnLinuxDistro.md
docs_src/getting-started/native/Ch-BuildRunOnWindows.md

fix: [main] Add starting core-common-config-bootstrapper to run native guides

---

mkdocs.yml

fix #1309, this PR fixes the render issue, but not sure the reason why fileCh-GettingStartedSDK still exists. (Could we trigger the Jenkins job again?)

fix: local render issue

---

docs_src/microservices/application/sdk/api/AppFunctionContextAPI.md

feat: [App SDK] Document new TriggerRetryFailedData API

---

docs_src/design/ucr/Device-Parent-Child-Relationships.md

We don't need "main" or "system" devices anymore.
It seemed less invasive to prevent deletion of devices with children (similar to how we prevent device profiles from being deleted if there are devices using them), instead of doing a cascading deletion.
Also minor formatting changes needed for mkdocs.

feat: Update UCR for parent-child to remove some requirements.

---

Jenkinsfile

fix: Set ENABLED_HTMLPROOFER=true only on PR validation

---

Jenkinsfile

Set ENABLED_HTMLPROOFER=true only on PR validation

fix: Set ENABLED_HTMLPROOFER=true only on PR validation(napa)

---

docs_src/microservices/configuration/CommonEnvironmentVariables.md

Close https://github.com/edgexfoundry/edgex-docs/issues/1365

docs: Add new EDGEX_OVERWRITE_CONFIG env

---

docs_src/getting-started/Ch-GettingStartedDockerUsers.md
docs_src/getting-started/Ch-GettingStartedHybrid.md
docs_src/security/Rootless-Docker.md
mkdocs.yml

Updated docs to use make run where needed
Closes #1364 
Docs need to be updated to reflect recent changes in edgex-compose repo

feat: Docker rootless

---

docs_src/microservices/general/database/Ch-Redis.md

fix: Updated Redis page

---

docs_src/microservices/device/sdk/devicesdk-getting-started/GettingStartedSDK-C.md

Due to the introduction of the common configuration in v3, the device service now requires either the `-cc/--commonConfig` or `-cp/--configProvider` flag during startup.

fix: Update GettingStartedSDK-C.md

---

docs_src/microservices/device/Configuration.md

feat: Add device up/down detection

---

docs_src/microservices/core/data/Configuration.md

Add Writable.EventPurge config usage for the PR https://github.com/edgexfoundry/edgex-go/pull/5059

feat: Add EventPurge config

---

docs_src/security/Ch-SecretStore.md
docs_src/security/Ch-Secure-Postgres.md
mkdocs.yml

Relates to #1410. Add doc for obtaining Postgres superuser password via secret store.

feat: Add doc for obtaining Postgres superuser pw

---

docs_src/security/Ch-Secure-Postgres.md

Relates to #1410. Add the client_token instruction to retrieve postgres credential.

fix: Add the client_token instruction

---

docs_src/microservices/core/data/Configuration.md
docs_src/microservices/core/data/details/DataRetention.md

Update default event retention duration to 168h.

feat: Update default event retention duration to 168h

---

docs_src/security/Ch-SecretStoreSetup.md
docs_src/security/security-file-token-provider.1.md
mkdocs.yml

Fixes #1425. Add doc for secretstore-setup regen token feature.

feat: Add doc for secretstore-setup regen token feature

---

docs_src/microservices/configuration/CommonConfiguration.md

Relates to #1428. Add more description about EnableNameFieldEscape service config.

fix: Add more description about EnableNameFieldEscape config

---

docs_src/microservices/device/services/device-rest/GettingStarted.md
docs_src/microservices/device/services/device-rest/howto/Testing.md

fixes https://github.com/edgexfoundry/edgex-docs/issues/1432
1. Update the API URL from api/v2 to api/v3
2. Add a new note to mention the solution for a possible error resposne as descrined in https://github.com/orgs/edgexfoundry/discussions/332

fix: update device-rest documentation with latest API version

---

docs_src/general/ServicePorts.md

Closes #1425. Add secretstore-setup service port to doc.

fix: Add secretstore-setup service port to doc

---

Dockerfile.docs

Security upgrade python from 3.10-slim to 3.13.3-slim

fix: Security upgrade python from 3.10-slim to 3.13.3-slim

---

docs_src/microservices/device/Configuration.md
docs_src/microservices/device/details/AutoEvents.md

Resolves #1468. Add docs for the new SendChangedReadingsOnly config.

feat: Add docs for the new SendChangedReadingsOnly config
