- .gitignore
- build.sh
> add the 'docs' subdirectory to match previous folder structure

- examples/Ch-ExamplesAddingMQTTDevice.rst
- examples/Ch-ExamplesAddingModbusDevice.rst
- examples/Ch-ExamplesAddingSNMPDevice.rst
- getting-started/Ch-GettingStartedUsers.rst
- getting-started/Ch-GettingStartedUsersNexus.rst
- quick-start/Ch-QuickStart.rst
- security/Ch-APIGateway.rst
- security/Ch-SecretStore.rst
- walk-through/Ch-WalkthroughRunning.rst
Applies changes from PR#12 to the Edinburgh branch.
Fixes #13
Signed-off-by: Michael Hall <mhall119@gmail.com>
> Update Docker Compose-file Locations

- Dockerfile.build
- build.sh
- examples/Ch-ExamplesAddingMQTTDevice.rst
- examples/Ch-ExamplesAddingModbusDevice.rst
- getting-started/Ch-GettingStartedSDK-C.rst
- quick-start/Ch-QuickStart.rst
- security/Ch-APIGateway.rst
- security/Ch-SecretStore.rst
- walk-through/Ch-WalkthroughRunning.rst
> fuji changes

- application/Ch-AppServiceConfigurable.rst
- application/Ch-ApplServices.rst
- application/Ch-ApplicationFunctionsSDK.rst
Closes #51 
Signed-off-by: Mike Johanson <michael.johanson@intel.com>
> docs: AppServices Update for Fuji

- design/adr/README.md
- design/adr/device-service/0002-Array-Datatypes.md
> Add ADR for array datatypes in Readings

- quick-start/Ch-QuickStart.rst
Add service default Port table to address issue #18 
Signed-off-by: [John Luo] <john@iotechsys.com>
> Add Default Port Table

- design/adr/README.md
- design/adr/core/0003-V2-API-Principles.md
Fix #79
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
> Added ADR for V2 API Specification

- docs/index.html
Creating the /docs folder with an index.html so that we can enable Github Pages on this repository.
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
> Add docs folder and index.html for Github Pages

- design/adr/0001-Registy-Refactor.md
Agreed process is to update the Decision section with why any updates are made to the ADR.
> doc(ADR Decision): Update the Decision section for previous update to keep -r

- examples/Ch-ExamplesAddingMQTTDevice.rst
- examples/Ch-ExamplesAddingModbusDevice.rst
- getting-started/Ch-GettingStartedSDK-C.rst
- quick-start/Ch-QuickStart.rst
- security/Ch-APIGateway.rst
- security/Ch-SecretStore.rst
- walk-through/Ch-WalkthroughRunning.rst
This comprises the changes made in [7b1b4b5](https://github.com/edgexfoundry/edgex-docs/commit/7b1b4b58c953ef204be10ddaa848353746f9f056) but without the build system changes. It addresses #64 and #65 
> Fuji doc changes

- docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
Fix #87 
- This is per https://github.com/edgexfoundry/edgex-go/issues/2328.
> Update docs to reflect the change in sending notifications of any severity level.

- Jenkinsfile
> re-implement pipeline to build and push changes to gh-pages branch

- api/Ch-APICoreCommand.rst
- api/Ch-APICoreData.rst
- api/Ch-APICoreMetadata.rst
- api/Ch-APISupportingServicesAlerts.rst
- api/Ch-APISupportingServicesLogging.rst
- api/Ch-APISupportingServicesScheduling.rst
- api/Ch-APISystemManagement.rst
> Add swaggerhub API url to the html pages.

- docs_src/design/adr/0005-Service-Self-Config.md
ADR approval
n/a
Issue Number:
none
ADR 0005
none
> changed status of ADR 0005 to approved

- docs_src/examples/Ch-ExamplesSendingAndConsumingBinary.md
Fix #113 
- Note that this update accompanies the work accompanying the `edge-go` issue for [Response of issueDeviceCommand is not providing CBOR Content-Type header](https://github.com/edgexfoundry/edgex-go/issues/2272), work that is currently being reviewed per two `PR`s (one each in `edge-go` and `device-sdk-go`.
- While this `PR` can be reviewed, the recommendation is to allow both `PR`s mentioned above to be merged _before_ merging this current `PR`.
> Update doc with steps for creating CBOR payload to use with PUT commands.

- docs_src/microservices/security/Ch-APIGateway.md
Fixes #123
Fixes #123
`Ch-APIGateway.md`
> fix: API Gateway documentation fixes

- docs_src/design/TOC.md
- docs_src/design/adr/devops/0007-Release-Automation.md
Updating the status of the ADR and adding it to the table of contents.
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
Issue Number:
> Update ADR 0007 status and add to table of contents

- docs_src/microservices/configuration/Ch-Configuration.md
- docs_src/microservices/core/data/Ch-CoreData.md
- docs_src/microservices/core/metadata/Ch-Metadata.md
- docs_src/microservices/support/logging/Ch-Logging.md
- docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
- docs_src/microservices/support/rulesengine/Ch-RulesEngine.md
- docs_src/microservices/support/scheduler/Ch-Scheduling.md
Fix #116 
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
- [X ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ X] Docs have been added / updated (for bug fixes / features)
- [X ] Documentation content changes
Issue Number: 116
> Update core/support config docs for Geneva release

- docs_src/getting-started/Ch-GettingStartedUsersNexus.md
- docs_src/microservices/configuration/Ch-Configuration.md
Links were incorrect
Issue Number: #147
Links are now correct
> docs: Updated links to the Geneva & Nightly Build compose files.

- docs_src/microservices/application/ApplicationFunctionsSDK.md
Issue Number: n/a
JSON Logic Section for App Func SDK
No
> docs: update JSON Logic note and tip

- docs_src/microservices/application/Configuration.md
- docs_src/microservices/application/GeneralAppServiceConfig.md
- mkdocs.yml
Add detailed configuration section for Application Services
Issue Number:  #155
> doc: Add detailed configuration section for Application Services

- docs_src/index.md
"Getting Started Guide" is just text rather than the link it should be as the surrounding text claims.
Issue Number:
"Getting Started Guide" has been made a link
No
> made Getting Started Guide link an actual link

- quick-start/Ch-QuickStart.rst
> fix the fuji docker-compose link

- docs_src/getting-started/quick-start/index.md
Issue Number:
html links to raw links for download
no
> docs: fix urls for quickstart

- docs_src/design/TOC.md
- docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md
> doc: Device Service REST API for v2.x

- docs_src/examples/AppServiceExamples.md
Issue Number: #234
Link point to new location
> fix: Fixed link to App Service examples

- versions.json
This needs to be manually updated as well for it to show up on the website.
Issue Number:
> build: add Hanoi version 1.3

- README.md
Versioning was a mystery on how it worked.
Issue Number:
Docs for how to version the docs site.
> docs: Add instructions on how to version EdgeX Docs site

- docs_src/microservices/application/GeneralAppServiceConfig.md
- docs_src/microservices/application/Triggers.md
Issue Number: #239
Add documentation of the App Service new MQTT Trigger capability.
No
> docs(AppServices): Document the App Services new MQTT Trigger capability

- docs/versions.json
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-docs/blob/master/.github/CONTRIBUTING.md.
> build: update versions.json to include 1.3

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-docs/blob/master/.github/CONTRIBUTING.md.
> feat: Document new HTTPPut pipeline function

- docs_src/microservices/security/edgex-secrets-config-proxy.1.md
- docs_src/microservices/security/edgex-secrets-config.1.md
Issue Number:
This proposal is related to addressing the following open EdgeX issues:
* https://github.com/edgexfoundry/edgex-go/issues/1926
* https://github.com/edgexfoundry/edgex-go/issues/2549
* https://github.com/edgexfoundry/edgex-go/issues/2477
* https://github.com/edgexfoundry/edgex-go/issues/2568
> feat: Proposal for new edgex-secrets-config utility.

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/application/ContextAPI.md
Not documented
#265 
Now documented!
> feat: New docs for ResponseContentType

- docs_src/microservices/configuration/Ch-Configuration.md
> fix(microservices): add serverBindAddr to common configuration

- Jenkinsfile
ci: Updating to edgeXGHPagesPublish shared library
Signed-off-by: Chinu Joy <chinu.joy@intel.com>
Moving to a shared library for GH Pages publish
> ci: Updating to edgeXGHPagesPublish shared library

- docs_src/design/TOC.md
- docs_src/design/adr/security/0016-docker-image-guidelines.md
> fix(adr): Move docker image guidelines to the security folder and add to TOC

- docs_src/design/adr/device-service/0002-Array-Datatypes.md
- docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md
- docs_src/design/adr/security/0008-Secret-Creation-and-Distribution.md
Approved ADRs still show `pending` status
Approved ADRs still show `approved` status
> fix(adr): Fix status of approved ADRs

- docs/index.html
Default is currently Geneva
Site will now select v1.3 by default
> build: update default version to v1.3

- docs_src/design/TOC.md
- docs_src/design/adr/013-Device-Service-Events-Message-Bus.md
ADR for designing how Device Services send Events via Message Bus
No
> feat(adr): Device Services send Events via Message Bus

- docs/versions.json
- mkdocs.yml
- versions.json
PRs will be now be going to v2.0 of docs site.
1.3 remains as default version until 2.0 is released.
> build: update version to 2.0

- docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md
Issue Number: #219 
- Use CamelCase for type names
- Clarify assertion behaviour
- Clarify overflow behaviour following data transforms
- Update Event/Reading with current DTO definitions
> fix(adr): Update ADR#11 following review

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/application/ContextAPI.md
MarkAsPushed feature has been removed from the App SDK but not the App Service docs
MarkAsPushed feature has been removed from App Service docs
> feat(microservices): Remove MarkAsPushed App Service documentation

- docs_src/design/adr/013-Device-Service-Events-Message-Bus.md
ADR doesn't have `SourceName` in the publish topic schema
ADR now has  `SourceName` in the publish topic schema
> feat: Add SourceName to publish topic schema

- docs_src/design/TOC.md
- docs_src/design/adr/security/0017-consul-security.md
> feat(adr): ADR for securing Consul

- docs_src/design/TOC.md
- docs_src/design/adr/device-service/0012-DeviceService-Filters.md
Big rewrite; inclusive of feedback from reviewers and ADR meeting
Rewrite from old ADR (see #269 for old comments and doc)
> feat(adr): addition of device service filter ADR

- docs_src/getting-started/Ch-GettingStartedUsers.md
fix: correct docker-compose file description
X86->ARM 64
Closes: #363
> fix: docker-compose file description mistake

- docs_src/design/TOC.md
- docs_src/design/adr/0018-Service-Registry.md
Signed-off-by: Tony Espy <espy@canonical.com>
This the initial draft PR for an ADR which discusses the existing behavior of EdgeX microservices with respect to the registry and associated client configuration read from configuration.toml files.
NA
> feat(adr): add Service Registry ADR

- docs_src/microservices/application/Triggers.md
Update custom trigger documentation to reflect v2 api changes.
Docs reflect v1 custom trigger API.
#368 
Includes v2 changes.
> fix(microservices): Update v2 Trigger Config

- README.md
> ci: Add badges to readme

- mkdocs.yml
> build: update google analytics to use v4 ID

- .github/Contributing.md
- .github/semantic.yml
Security scope now exist
Security scope doesn't exist
> feat: Add Security scope for conventional commits.

- docs_src/security/Ch-Configuring-Add-On-Services.md
- docs_src/security/Ch-Secure-MessageBus.md
- mkdocs.yml
Secure MessageBus section doesn't exist
Secure MessageBus section now exists
> feat(security): Add new Secure MessageBus section

- docs_src/microservices/application/AdvancedTopics.md
Update background publisher example to use v2 API.
#412 
> feat(api): Update Background Publisher Example

- docs_src/microservices/application/ContextAPI.md
Add documentation for v2 context storage and update context page for v2
in general.
#396
Adds documentation for new context storage API and generally updates for v2 context.
> feat(api): Document V2 Context API

- docs_src/microservices/application/ContextAPI.md
Add CorrelationID() summary to Miscellaneous section.
#411 
- [ x No
> feat(api): Document CorrelationID

- docs_src/microservices/application/ApplicationServices.md
New features reference in the new version of the Intro but not highlighted as new.
New features reference in the Intro now highlighted in `edgey` note
> feat: Add what's new edgey note to App Services Introduction

- docs_src/microservices/application/ApplicationServices.md
- docs_src/security/Ch-Secure-MessageBus.md
No edgey note used
edgey note added
> feat: Update Secure MessageBus section with an edgey note

- docs_src/microservices/application/GeneralAppServiceConfig.md
Configuration doc out of date for Ireland
Configuration doc up to date for Ireland
> feat: Update the App Service Configuration documentation for Ireland changes

- docs_src/microservices/application/Triggers.md
Trigger documentation stale for V2
Trigger documentation up-ti-date for V2
> feat: Update App Service Trigger documentation

- docs_src/microservices/application/AdvancedTopics.md
Update background publishing example to 2.0 sdk
> fix(api): Update Background Publisher Example

- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/ApplicationServiceAPI.md
Broken links and examples are not consistent.
Links fixed, examples consistent and little bit more content.
> refactor: Final tweaks for links and examples, etc

- docs_src/microservices/application/Triggers.md
closes 
Signed-off-by: lenny <leonard.goodell@intel.com>
Filter by Topic need more clarification around wildcard characters used for Redis vs MQTT
Filter by Topic  clarification around wildcard characters used for Redis vs MQTT added in notes.
> feat: Add notes for Filter By Topics for the different wildcards

- docs_src/examples/AppServiceExamples.md
App Services Examples out of date
App Services Examples updated for Ireland
> feat: Update App Services Examples for Ireland

- docs_src/microservices/device/V2Migration.md
- docs_src/microservices/device/profile/Ch-DeviceProfile.md
- docs_src/microservices/device/profile/Ch-DeviceProfileRef.md
> feat: add device service migration guide

- docs_src/general/ServiceConfiguration.md
Service Configuration section not updated for V2
Service Configuration section now updated for V2
> feat: Update Service Configuration section for V2

- docs_src/general/ContainerNames.md
ContainerNames.md  not updated for V2
ContainerNames.md  now updated for V2
> feat: Update ContainerNames.md for V2

- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/GettingStarted.md
- docs_src/microservices/application/Triggers.md
- docs_src/microservices/application/V2Migration.md
fix grammar/missing words, change format of App Context API to match App Service API
Addresses Issue 509
API documentation is not consistent, grammatical and formatting issues 
fix grammar and formatting, change format of App Context API to match App Service API
> fix: minor edits and formatting changes in app services

- docs_src/assets/stylesheets/newexample.css
- mkdocs.yml
this is done so that it differs significantly from the edgey 2.0 admonition
- [x ] No
> feat: change example admonition to khaki

- docs_src/api/applications/Ch-APIAppFunctionsSDK.md
- docs_src/api/core/Ch-APICoreCommand.md
- docs_src/api/core/Ch-APICoreData.md
- docs_src/api/core/Ch-APICoreMetadata.md
- docs_src/api/devices/Ch-APIDeviceSDK.md
- docs_src/api/management/Ch-APISystemManagement.md
- docs_src/api/support/Ch-APISupportNotifications.md
- docs_src/api/support/Ch-APISupportScheduler.md
- docs_src/microservices/device/Ch-DeviceServices.md
- docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
- docs_src/microservices/support/scheduler/Ch-Scheduler.md
- docs_src/walk-through/Ch-WalkthroughCommands.md
- docs_src/walk-through/Ch-WalkthroughData.md
- docs_src/walk-through/Ch-WalkthroughDeviceProfile.md
- docs_src/walk-through/Ch-WalkthroughDeviceService.md
- docs_src/walk-through/Ch-WalkthroughProvision.md
- docs_src/walk-through/Ch-WalkthroughReading.md
> fix: add version to swagger links

- GOVERNANCE.md
- OWNERS.md
LF Edge required documentation pages added to the repository (Governance and Owners)
> feat: added LF Edge required Governance and Owners MD pages

- docs_src/examples/Ch-ExamplesModbusdatatypeconversion.md
Close: #491
Signed-off-by: weichou <weichou1229@gmail.com>
Add note for Modbus data type conversion doc
> feat: Add note for Modbus data type conversion doc

- docs_src/microservices/device/profile/Ch-DeviceProfileRef.md
> fix: Add the missing field 'readwrite' to device command

- docs_src/microservices/device/Ch-DeviceServices.md
> fix: Remove operating state from device service

- docs_src/microservices/device/profile/Ch-DeviceProfileRef.md
> fix: Add a statement for name fields of device profile, device resource and device command

- docs_src/getting-started/ApplicationFunctionsSDK.md
App SDK Getting started not updated for V2
App SDK Getting started now updated for V2
> feat: Update App SDK Getting started for V2

- docs_src/getting-started/Ch-GettingStartedSDK-C.md
- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/microservices/device/Ch-DeviceServices.md
New structured custom configuration feature for Device Services not documented
New structured custom configuration feature for Device Services now documented
> feat: Document Device Service structured custom configuration

- docs_src/getting-started/Ch-GettingStartedUsers.md
> fix: Correct typo in branch name from Ireland to ireland

- .github/PULL_REQUEST_TEMPLATE.md
Updated the PR template to the new version and replaced checklist with more appropriate item for docs.
> ci: Update PR template

- docs_src/security/Ch-APIGateway.md
fix https://github.com/edgexfoundry/edgex-docs/issues/590
Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>
> feat: Document the the Kong worker process setting

- docs_src/microservices/configuration/CommonConfiguration.md
related to https://github.com/edgexfoundry/edgex-go/issues/3710
> fix: Document the MaxResultCount default value to be new value used

- docs/versions.json
> build: Add Jakarta to doc pages drop down

- docs_src/microservices/application/Triggers.md
Adds note to docs about cloning behavior for multi-pipeline support in
custom triggers and nil behavior.
> feat(api): Add Note About Context Cloning

- docs_src/microservices/support/scheduler/Ch-Scheduler.md
> fix(microservices): fixed data dict table in scheduler page

- docs_src/index.md
> fix: Remove disclaimer and update description for edgey notes

- docs_src/microservices/application/Triggers.md
Include new MessageReceived handler for multi-pipeline support.
> feat(api): Update Custom Trigger Docs

- docs_src/microservices/device/V2Migration.md
> fix: (migration) add note on OperatingState values

- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/security/Ch-CORS-Settings.md
- mkdocs.yml
Create a page to introduce CORS enabling
Close https://github.com/edgexfoundry/edgex-docs/issues/608
Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>
> feat(security): Create doc about CORS settings

- docs_src/microservices/device/Ch-DeviceServices.md
> feat: Add reference to instance names for dev svcs

- docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
- Update simulator script
- Update profile example
Closes: #634
Signed-off-by: bruce <weichou1229@gmail.com>
> feat(microservices): Update MQTT doc for new Object reading type

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
Signed-off-by: Mengyi <mengyi.wang@canonical.com>
```
sudo pip install mkdocs-material==5.1.0
mkdocs serve
```
Then, open [this link](http://127.0.0.1:8000/edgex-docs/getting-started/tools/Ch-GUI/) in your browse
> feat(walkthru): update GettingStartedSnapUsers 

- docs/index.html
- docs/versions.json
- mkdocs.yml
- versions.json
- [n/a] Changes have been rendered and validated locally using mkdocs-material (see edgex-docs README)
> build: Switch Doc Development to Kamakura

- docs_src/microservices/application/BuiltIn.md
Closes https://github.com/edgexfoundry/app-functions-sdk-go/issues/968
> fix: Update link to post-release security advisory.

- docs_src/security/Ch-SecretStore.md
> fix: Correct syntax to get shell in edgex-vault (branch:main)

- docs_src/security/Ch-SecretStore.md
> fix: Correct syntax to get shell in edgex-vault (branch: jakarta)

- docs_src/security/Ch-SecretStore.md
> fix: Correct syntax to get shell in edgex-vault (branch: ireland)

- docs_src/design/adr/security/0019-spiffe.md
Closes #278
ADR for to support delayed-start EdgeX services.
> feat: Approval for delayed services start ADR

- docs_src/api/applications/Ch-APIAppFunctionsSDK.md
- docs_src/api/core/Ch-APICoreCommand.md
- docs_src/api/core/Ch-APICoreData.md
- docs_src/api/core/Ch-APICoreMetadata.md
- docs_src/api/devices/Ch-APIDeviceSDK.md
- docs_src/api/management/Ch-APISystemManagement.md
- docs_src/api/support/Ch-APISupportNotifications.md
- docs_src/api/support/Ch-APISupportScheduler.md
- docs_src/microservices/application/ApplicationFunctionsSDK.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/device/Ch-DeviceServices.md
- docs_src/microservices/device/V2Migration.md
- docs_src/microservices/device/virtual/Ch-VirtualDevice.md
- docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
- docs_src/microservices/support/scheduler/Ch-Scheduler.md
- docs_src/walk-through/Ch-WalkthroughCommands.md
- docs_src/walk-through/Ch-WalkthroughDeviceProfile.md
- docs_src/walk-through/Ch-WalkthroughDeviceService.md
- docs_src/walk-through/Ch-WalkthroughProvision.md
- docs_src/walk-through/Ch-WalkthroughReading.md
> fix: update all swagger refs to 2.1.0

- docs_src/microservices/configuration/ConfigurationAndRegistry.md
Signed-off-by: maoxudong <maoxudong0813@163.com>
> fix: fixed clerical error where version 30 -> version 3.0

- docs_src/security/Ch-APIGateway.md
> fix: Pass Kong admin JWT to secrets-config utility (jakarta)

- docs_src/security/Ch-APIGateway.md
> fix: Pass Kong admin JWT to secrets-config utility (main/kamakura)

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> fix: Refactor snap getting started

- docs_src/security/Ch-SSH-Tunneling-HowToSecureDeviceServices.md
- mkdocs.yml
> fix: Update remote device service example for Jakarta

- docs_src/api/applications/Ch-APIAppFunctionsSDK.md
- docs_src/api/core/Ch-APICoreCommand.md
- docs_src/api/core/Ch-APICoreData.md
- docs_src/api/core/Ch-APICoreMetadata.md
- docs_src/api/devices/Ch-APIDeviceSDK.md
- docs_src/api/management/Ch-APISystemManagement.md
- docs_src/api/support/Ch-APISupportNotifications.md
- docs_src/api/support/Ch-APISupportScheduler.md
> feat(api): Adjust all swagger links to be for version 2.2.0

- docs_src/design/adr/0018-Service-Registry.md
- docs_src/design/adr/core/0019-EdgeX-CLI-V2.md
- docs_src/design/adr/device-service/0012-DeviceService-Filters.md
these ADRs are approved and the voting record was checked for exact approval dates
> fix(adr): fix the status of approved ADRs

- docs_src/microservices/application/ApplicationServiceAPI.md
Related to this PR: https://github.com/edgexfoundry/app-functions-sdk-go/pull/1039
> feat: Document new RequestTimeout Application Service API

- docs_src/getting-started/quick-start/index.md
> fix(ref): fix jakarta docs getting started guide

- docs_src/general/ServicePorts.md
> feat(security): Allocate ports for delayed service start ADR

- docs_src/design/TOC.md
- docs_src/design/adr/core/0021-Device-Profile-Changes.md
> feat(adr): revised and simplified device profile changes ADR

- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
> feat(examples): add ProtocolProperties validation mechanism

- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
> feat(examples): update device validation example

- docs_src/microservices/application/Triggers.md
fix: #704 
Signed-off-by: Felix Ting <felix@iotechsys.com>
> feat: Update External MQTT Trigger Docs

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/ApplicationServiceAPI.md
Add new method on ApplicationService interface to docs page.
> feat(microservices): Custom Store/Forward Client Registration

- docs_src/examples/Ch-ExamplesAddingModbusDevice.md
Update Modbus RTU usage to match the docker-compose settings.
Signed-off-by: bruce <weichou1229@gmail.com>
> feat: Update Modbus RTU usage

- docs_src/microservices/application/GeneralAppServiceConfig.md
- docs_src/microservices/application/Triggers.md
- Update the description of the retry mechanism
- Add `RetryDuration` and `RetryInterval` configuration for External MQTT Trigger
Signed-off-by: Felix Ting <felix@iotechsys.com>
> fix: Update External MQTT Trigger Docs

- docs_src/microservices/device/sdk/Ch-DeviceSDK.md
- docs_src/microservices/device/sdk/Ch-Ref-SDK-C.md
- docs_src/microservices/device/sdk/Ch-Using-iot-data-t.md
This addresses part of #598 (No API documentation)
> feat(api): add reference material for device-sdk-c

- docs_src/walk-through/Ch-WalkthroughDeviceService.md
> fix(walkthru): walkthrough json body example fix

- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/core/data/Ch-CoreData.md
- docs_src/microservices/general/index.md
> feat: Document new Service Metrics capability

- docs_src/microservices/core/metadata/Ch-Metadata.md
- docs_src/microservices/device/Ch-DeviceServices.md
> fix: add Edgex 2.2 notes to configs for device profile changes

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/ApplicationServiceAPI.md
- docs_src/microservices/application/GeneralAppServiceConfig.md
- docs_src/microservices/general/index.md
Completes https://github.com/edgexfoundry/app-functions-sdk-go/issues/1084
> feat: Document new Custom Application Service Metrics capability

- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/core/data/Ch-CoreData.md
- docs_src/microservices/device/Ch-DeviceServices.md
> feat: Add MaxEventSize to device service and update MaxRequestSize config

- Jenkinsfile
> ci: update to ubuntu based agent

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/general/index.md
> refactor: Update Metrics documentation for recent refactoring

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
> feat: Document new MergeOnSend setting for App Services Batch function

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/GeneralAppServiceConfig.md
> feat: Document new built-in metrics for application services

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
> feat: Document new ToLineProtocol function and metrics-influxdb profile

- docs_src/general/ServicePorts.md
> feat: Add port numbers for new services

- docs/index.html
- docs/versions.json
This PR updates the versions file and index.html to the current release version 2.2
> ci: automated version file changes for [2.3]

- docs_src/general/ServicePorts.md
> fix: Fix typos in Default Service Ports from previous PR (Levski)

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/general/index.md
> feat: Add notes to metrics sections that it is Beta released [Kamakura]

- mkdocs.yml
> build: Publish to 2.3 version

- docs_src/general/ServicePorts.md
> fix: Fix typos in Default Service Ports from previous PR (kamakura)

- docs_src/microservices/application/AppFunctionContextAPI.md
Add note on Clone method to AppFunctionContext api doc.
> feat(microservices): Add Clone to AppFunctionContext [KAMAKURA]

- docs_src/microservices/application/AppFunctionContextAPI.md
Add note on Clone method to AppFunctionContext api doc.
* having trouble running using latest changes right now
> feat(microservices): Add Clone to AppFunctionContext

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> feat: Getting started - Snap add-on service (Kamakura)

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
- add sudo to get commands
- separate temp variables to allow reverting values
- add a verification step
- fix typo
> fix: corrections in Getting started - Snap add-on service (Kamakura)

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> feat: Add device-virtual in snap getting started

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
Depends on:
- https://github.com/edgexfoundry/device-usb-camera/pull/30
> feat: Add snap docs for Device USB Camera

- docs_src/design/adr/013-Device-Service-Events-Message-Bus.md
- docs_src/microservices/device/profile/Ch-DeviceProfileRef.md
- mkdocs.yml
Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>
> feat: add fixes and exclusions for htmlproofer

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/GeneralAppServiceConfig.md
> feat: Document new additional App Service metrics

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> feat: Add snap docs for Device ONVIF Camera

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
> feat: docs for built-in pipeline function to wrap event

- docs_src/microservices/device/sdk/SDK-Go-API.md
- mkdocs.yml
Addresses documentation for https://github.com/edgexfoundry/device-sdk-go/issues/1168
> feat: Document API for Device SDK Go

- Jenkinsfile
> ci: add retry to mkdocs build stage

- docs_src/microservices/application/Triggers.md
Lists new options, build flag and simple jetstream example.  Links to
README for complete option listing.
> feat(microservices): Add NATS MessageBus Overview for App Service Trigger

- docs_src/microservices/support/scheduler/Ch-Scheduler.md
> fix: Remove scheduler unused fields and update data dictionary

- mkdocs.yml
> feat: add google analytics to the geneva release docs

- mkdocs.yml
> feat: add google analytics to the hanoi release docs

- mkdocs.yml
> feat: add google analytics to the ireland release docs

- mkdocs.yml
> feat: add google analytics to the jakarta release docs

- mkdocs.yml
> ci: revert google analytics config change for geneva

- mkdocs.yml
> feat: update the google code for analytics

- docs_src/microservices/core/metadata/Ch-Metadata.md
> feat: document core metadata units of measure capability

- docs_src/security/Ch-Secure-Consul.md
close #3158
Signed-off-by: Valina Li <valina.li@intel.com>
> docs: add management token

- docs_src/getting-started/Ch-GettingStartedDockerUsers.md
fix #848 
Signed-off-by: melody <melody@iotechys.com>
> docs: add warning to GettingStartedusingDocker.md

- docs_src/getting-started/Ch-GettingStartedUsers.md
fix #848
Signed-off-by: melody <melody@iotechsys.com>
> docs[jakarta]: add warning to GettingStartedUsers.md

- docs_src/getting-started/Ch-GettingStartedDockerUsers.md
fix #848
Signed-off-by: melody <melody@iotechsys.com>
> docs[kamakura]: add warning to GettingStartedDockerUsers.md

- docs_src/examples/index.md
> fix: [Jakarta] restore link to old K8s example

- docs_src/microservices/general/messagebus.md
> fix: Correct relative link to snap configuration

- docs_src/design/TOC.md
- docs_src/design/ucr/0005-Record-and-Replay.md
- docs_src/design/ucr/Record-and-Replay.md
> feat: Create Record and Replay UCR

- docs_src/microservices/device/Ch-DeviceServiceList.md
Applying same changes to `main` as this PR #850 did for `kamakura`
closes #842
> refactor: [main] Rework device service list and add new camera device services

- docs_src/microservices/application/ApplicationServiceAPI.md
> fix: Correct typo in CommandClient function description

- docs_src/examples/Ch-ExamplesUsbDeviceService.md
- mkdocs.yml
Signed-off-by: brianointel <brian.j.osburn@intel.com>
> docs: added usb camera streaming guide

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
Related to https://github.com/edgexfoundry/edgex-ui-go/pull/553
> feat: Extend EdgeX UI snap getting started for disabled service and security

- .github/semantic.yml
> feat: Add new ucr scope for Conventional Commits

- docs_src/examples/Ch-OSImageWithEdgeX.md
- mkdocs.yml
> feat: Example for creating an EdgeX OS image

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> feat: Add ASC device filtering via snap options

- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/device/sdk/SDK-Go-API.md
- docs_src/microservices/general/index.md
Also update other metrics document to be current for 2.3
> feat: Add Device Service custom metrics section

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> feat: Use MQTT message bus via snap options

- docs_src/microservices/general/messagebus.md
Adds NKeySeedFile and CredentialsFile to the SecurityConfiguration table for NATS.  Also adds notes on resource provisioning using nats-box.
> feat(microservices): Document NATS Authentication Modes

- docs_src/design/TOC.md
- docs_src/design/adr/application/0025-Record-and-Replay.md
> feat: Create Record and Replay ADR

- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/core/data/Ch-CoreData.md
- docs_src/microservices/core/metadata/Ch-Metadata.md
- docs_src/microservices/general/index.md
- docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
- docs_src/microservices/support/scheduler/Ch-Scheduler.md
> feat: Document new common service metrics

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> feat: Add disabling registry and config provider Consul in snap getting started

- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/microservices/application/GeneralAppServiceConfig.md
- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/device/Ch-DeviceServices.md
These are the fisrt built-in
Also updated metrics docs for consitency
> feat: Document Device Service EventsSent and ReadingsSent metrics

- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/general/index.md
closes: edgexfoundry#374
Signed-off-by: Valina Li <valina.li@intel.com>
> docs: add security consul metrics

- docs_src/V2TopLevelMigration.md
> docs: add details on v2 Event/Reading DTOs

- docs_src/walk-through/Ch-WalkthroughReading.md
> docs: fully document origin timestamp

- docs_src/design/adr/README.md
- docs_src/microservices/device/Ch-DeviceServices.md
close #893 
Signed-off-by: melody <melody@iotechsys.com>
> fix: Env EDGEX_INSTANCE should be EDGEX_INSTANCE_NAME

- docs_src/microservices/core/metadata/Ch-Metadata.md
- docs_src/security/Ch-SecurityIssues.md
> fix: Correct broken link

- docs_src/microservices/application/V2Migration.md
> fix: Clarify change to use of dtos.Event in pipeline functions

- docs/versions.json
- mkdocs.yml
- template_macros.yaml
This PR updates the version files to the next release version 2.4
> ci: automated version file changes for [2.4]

- docs_src/general/ServicePorts.md
- docs_src/getting-started/Ch-GettingStartedDevelopers.md
- docs_src/getting-started/native/Ch-BuildRunOnArm32.md
- docs_src/getting-started/native/Ch-BuildRunOnLinuxDistro.md
- docs_src/index.md
- docs_src/microservices/application/Triggers.md
- docs_src/microservices/core/data/Ch-CoreData.md
- docs_src/microservices/general/messagebus.md
- docs_src/microservices/support/eKuiper/Ch-eKuiper.md
> feat: Remove ZeroMQ from documentation

- docs_src/microservices/application/ApplicationServiceAPI.md
> fix: remove references to LoadConfigurablePipeline

- docs_src/design/TOC.md
- docs_src/design/ucr/Common Configuration.md
- docs_src/design/ucr/Global Common Configuration.md
> feat: Common Configuration UCR

- docs_src/robots.txt
> fix: add robots.txt in order to have search engines use latest docs

- docs_src/design/TOC.md
- docs_src/design/ucr/Microservice-Authentication.md
> feat(ucr): UCR for microservice authentication

- docs/versions.json
- mkdocs.yml
- template_macros.yaml
> refactor: Update Minnesota version of docs to be 3.0

- docs_src/microservices/device/sdk/Ch-Ref-SDK-C.md
- docs_src/microservices/device/sdk/Ch-Using-iot-data-t.md
https://github.com/edgexfoundry/device-sdk-c/pull/435
> fix: update C SDK doc in line with device-sdk-c PR 435

- docs_src/microservices/application/ApplicationServiceAPI.md
> fix: remove references to deprecated StoreSecret Code

- docs_src/getting-started/tools/Ch-GUI.md
> fix: fix broken eKuiper link

- docs_src/microservices/application/BuiltIn.md
> fix: remove old NewTags and rename NewGenericTags to NewTags

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
- docs_src/microservices/device/Ch-DeviceServices.md
- docs_src/security/Ch-Configuring-Add-On-Services.md
- docs_src/security/SeedingServiceSecrets.md
> refactor: Update for SecretStore no longer in configuration files.

- docs/robots.txt
> fix: add sitemap to robots.txt to allow for Google rescan

- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
- docs_src/security/secrets-config-proxy.md
- docs_src/security/security-file-token-provider.1.md
related: https://github.com/edgexfoundry/go-mod-bootstrap/pull/406
> docs: Update docs for changes of renaming config options in 3.0

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/ApplicationServiceAPI.md
- docs_src/microservices/application/Triggers.md
- docs_src/microservices/general/messagebus.md
> docs: Update Redis Pub/sub topic wild cards to match that of MQTT

- docs_src/microservices/core/metadata/Ch-Metadata.md
corresponding change of edgexfoundry/edgex-go#4316
> feat: remove Notifications configuration in Metadata

- docs_src/api/Ch-APIIntroduction.md
- docs_src/getting-started/tools/Ch-GUI.md
- docs_src/microservices/application/AdvancedTopics.md
Closes: #951
Signed-off-by: Valina Li <valina.li@intel.com>
> feat: Remove old Metrics endpoint documentation

- docs_src/microservices/core/metadata/Ch-Metadata.md
> feat: Update Core Metadata Device System Event DTO

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> fix: Add an extra line for snap docs' format

- mkdocs.yml
> feat: include version in site_url for sitemap.xml

- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
> docs: Update device-usb-camera's file list in snap getting started

- docs_src/getting-started/configuration.toml
- docs_src/getting-started/tools/Ch-CommandLineInterface.md
- docs_src/microservices/core/metadata/Ch-Metadata.md
- docs_src/microservices/device/Ch-DeviceServices.md
- docs_src/security/Ch-RemoteDeviceServices.md
> feat: Remove LastConnected and LastReported configs

- docs_src/design/adr/security/0028-authentication.md
> feat: TSC approval of microservice auth ADR

- docs_src/microservices/general/messagebus.md
related to edgexfoundry/device-sdk-go#1261
> feat: add an additional level in event publish topic

- mkdocs.yml
> fix: fix sitemap for Hanoi release to have version in sitemap.xml

- mkdocs.yml
> fix: fix sitemap for Jakarta release to have version in sitemap.xml

- docs_src/microservices/device/profile/Ch-DeviceProfile.md
- docs_src/microservices/device/profile/Ch-DeviceProfileRef.md
related to edgexfoundry/go-mod-core-contracts#770
> feat: ResourceProperties data type changes

- docs_src/microservices/device/Ch-DeviceServices.md
related to edgexfoundry/device-sdk-go#1271
> feat: device service publish event with updated value for PUT command

- docs_src/design/adr/core/0022-UoM.md
- docs_src/design/ucr/URIs-for-Files.md
- docs_src/microservices/core/metadata/Ch-Metadata.md
BREAKING CHANGE: Update UoM doc to use yaml instead of toml format.
> feat!: Update UoM doc for v3 changes

- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
> feat: Added common config flag

- docs_src/microservices/device/profile/Ch-DeviceProfileRef.md
> feat: Change minimun and maximum data types in ResourceProperties

- docs_src/microservices/core/command/Ch-Command.md
related to edgexfoundry/edgex-go#4279
> feat: Regex Get Command

- docs_src/microservices/configuration/CommonConfiguration.md
> refactor: Update common config section to show change of DB Timeout to a duration

- docs_src/microservices/configuration/CommonEnvironmentVariables.md
- docs_src/microservices/configuration/ConfigurationAndRegistry.md
> feat: Update Configuration docs for recent change to when Overrides are applied

- docs_src/general/ServiceConfiguration.md
- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/ApplicationServiceAPI.md
- docs_src/microservices/application/GeneralAppServiceConfig.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
- docs_src/microservices/configuration/ConfigurationAndRegistry.md
- docs_src/microservices/core/metadata/Ch-Metadata.md
- docs_src/security/Ch-APIGateway.md
Docs under `Design` folder are out of scope for this.
> feat: Update docs for change from TOML to YAML files

- docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
- docs_src/examples/Ch-ExamplesAddingModbusDevice.md
- docs_src/examples/Ch-ExamplesUsbDeviceService.md
- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/microservices/device/Ch-DeviceServices.md
> refactor: More update for YAML files

- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/application/Triggers.md
- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/general/index.md
- docs_src/microservices/general/messagebus.md
- docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
- docs_src/security/Ch-RemoteDeviceServices.md
- docs_src/security/secrets-config-proxy.md
- docs_src/security/security-file-token-provider.1.md
> refactor: More TOML to YAML changes

- Jenkinsfile
> fix: Disable htmlproofer for now

- docs_src/security/Ch-Configuring-Add-On-Services.md
> fix: compact service list separator character (kamakura)

- docs_src/security/Ch-Configuring-Add-On-Services.md
> fix: compact service list separator character (jakarta)

- docs_src/security/Ch-Configuring-Add-On-Services.md
> fix: compact service list separator character (minnesota)

- docs_src/security/Ch-Configuring-Add-On-Services.md
> fix: compact service list separator character (levski)

- docs_src/microservices/support/scheduler/Ch-Scheduler.md
> feat: Document IntervalAction.AuthMethod

- docs_src/api/core/Ch-APICoreConfigurationAndRegistry.md
> fix: Fix broken Consul links

- docs_src/microservices/core/command/Ch-Command.md
> fix: update example ReceivedTopic in Commands via Messaging

- docs_src/security/Ch-SecretProviderApi.md
> refactor: Update SecretProvider API documentation

- docs_src/microservices/configuration/CommonEnvironmentVariables.md
> feat: Document  EDGEX_DISABLE_JWT_VALIDATION

- docs_src/design/adr/014-Secret-Provider-For-All.md
- docs_src/getting-started/Ch-GettingStartedSnapUsers.md
- docs_src/security/Ch-APIGateway.md
- docs_src/security/Ch-Configuring-Add-On-Services.md
- docs_src/security/Ch-Secure-Consul.md
BREAKING CHANGE: Add EDGEX_ prefix to ADD_SECRETSTORE_TOKENS, ADD_REGISTRY_ACL_ROLES, ADD_KNOWN_SECRETS, ADD_PROXY_ROUTE, and IKM_HOOK variables
> refactor(security)!: Prefix security related env vars with EDGEX_

- Jenkinsfile
- mkdocs.yml
> ci: debug htmlproofer response codes

- docs_src/design/adr/0023-North-South-Messaging.md
> fix: Remove dead iotaap.io link

- docs_src/security/Ch-APIGateway.md
> fix: API gateway JWT documentation for EdgeX 3.0

- docs_src/security/Ch-Authenticating.md
> feat: Add link to snap authentication

- docs_src/security/Ch-Authenticating.md
> feat: Expand authenticating section for EdgeX UI use cases

- docs_src/getting-started/Ch-GettingStartedSDK-C.md
- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/microservices/device/Ch-DeviceServiceList.md
> fix: Resolve broken links using wrong version tag

- docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
> fix: Remove references to single level topics for device mqtt

- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
- docs_src/microservices/device/Ch-DeviceServices.md
- docs_src/threat-models/secret-store/vault_master_key_encryption.md
> feat: Refine the Config and Env Var docs

- Jenkinsfile
- mkdocs.yml
> fix: Disable link validation until many broken links can be addressed

- docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
> feat: Update MQTT Add Device docs for new multi-reading async capability

- docs_src/microservices/application/ApplicationServiceAPI.md
> feat: Document the new App SDK RemoveAllFunctionPipelines API

- docs_src/general/ContainerNames.md
Also added missing containers
close #1026
> refactor: Update the Container Names page to reflect V3 names

- docs_src/getting-started/Ch-GettingStartedHybrid.md
> feat: Update Hybrid doc for running with Common Config

- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/general-usage.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/api-analytic-support.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/api-event-handling.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/api-usage-user-handling.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/auto-discovery.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/credentials.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/custom-metadata-feature.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/friendlyname-mac.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/getting-started-with-docker-security.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/reboot-needed.md
These changes are related to https://github.com/edgexfoundry/device-onvif-camera/pull/347 which fixes the issue - https://github.com/edgexfoundry/device-onvif-camera/issues/173
> docs: Fixed device-onvif docs with updated Edgex commands and changed the version of apis to v3 

- docs_src/microservices/device/sdk/SDK-Go-API.md
> docs: add PatchDevice and DeviceExistsForName and refactor UpdateDeviceOperatingState

- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/application/V3Migration.md
> feat: Add V3 App Service Migration doc

- docs_src/V3TopLevelMigration.md
> feat: Add v3 Migration section for Command Line options and Envs

- docs_src/microservices/core/metadata/Ch-Metadata.md
> feat: Update ProvisionWatcher in Metadata Data Dictionary

- docs_src/microservices/configuration/V3MigrationCommonConfig.md
> feat: Create V3 Migration guide for Common Configuration

- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/deployment.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/auto-discovery.md
Closes https://github.com/edgexfoundry/device-onvif-camera/issues/364
> docs: ONVIF add curl command replacement for scripts

- docs_src/V3TopLevelMigration.md
- docs_src/microservices/device/V3Migration.md
- docs_src/microservices/device/sdk/SDK-Go-API.md
> feat: More V3 device service migration content

- docs_src/microservices/general/messagebus.md
> fix: Update MessageBus to show MQTT is secured in secure mode

- docs_src/security/Ch-Secure-MessageBus.md
> fix: Remove note about MQTT MessageBus not secure

- docs_src/examples/index.md
> fix: Remove links to removed examples

- docs_src/microservices/device/V3Migration.md
- docs_src/microservices/device/supported/device-onvif-camera/swagger.md
> feat: add v3 migration guide for device-onvif-camera

- docs_src/microservices/device/V3Migration.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/deployment.md
> feat: USB v3 migration guide

- docs_src/microservices/core/command/Ch-Command.md
- docs_src/security/SeedingServiceSecrets.md
> docs: Command service connects to secure external MQTT broker

- docs/versions.json
> fix: update versions.json to point latest to 3.0 release

- docs_src/microservices/device/V3Migration.md
> docs: Add V3 migration section for C SDK

- versions.json
> ci: Add Napa to releases drop down

- template_macros.yaml
> ci: set version macro to 3.0

- docs_src/general/ServicePorts.md
> fix: [main] Correct published port number for Device GPIO

- docs_src/general/ServicePorts.md
> fix: [minnesota] Correct published port number for Device GPIO

- docs_src/general/ServicePorts.md
> fix: [levski] Correct published port number for Device GPIO

- docs_src/general/ServicePorts.md
> fix: [jakarta] Correct published port number for Device GPIO

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/application/Triggers.md
> fix: [minnesota] Address missed secretPath renaming in App Services

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
- docs_src/microservices/application/Triggers.md
> fix: [main] Address missed secretPath renaming in App Services

- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
> fix: [main] Add missing flags for running in hybrid mode to SDK Go Getting Started

- docs_src/general/ServiceConfiguration.md
- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/GettingStarted.md
- docs_src/microservices/application/Triggers.md
- docs_src/security/Ch-Configuring-Add-On-Services.md
- docs_src/security/Ch-SecretStore.md
> fix: [minnesota] Replace all instances of `master` in edgex repo links  with {{version}}

- docs_src/general/ServiceConfiguration.md
- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/GettingStarted.md
- docs_src/microservices/application/Triggers.md
- docs_src/security/Ch-Configuring-Add-On-Services.md
- docs_src/security/Ch-SecretStore.md
Commit Message Description (imported automatically by GitHub) -->
> fix: [main] Replace all instances of master in edgex repo links with {{version}}

- docs_src/examples/app-service-examples/camera-management/Ch-CameraManagement.md
> feat: fix cd command

- docs_src/V3TopLevelMigration.md
- docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
- docs_src/examples/Ch-ExamplesAddingModbusDevice.md
- docs_src/getting-started/Ch-GettingStartedDockerUsers.md
- docs_src/getting-started/Ch-GettingStartedHybrid.md
- docs_src/getting-started/Ch-GettingStartedSDK-C.md
- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/getting-started/Ch-GettingStartedUsersNexus.md
- docs_src/getting-started/quick-start/index.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/deployment.md
- docs_src/security/Ch-RemoteDeviceServices.md
> refactor: [minnesota] Replace use of `docker-compose` command with `docker compose` CLI command

- docs_src/V3TopLevelMigration.md
- docs_src/examples/Ch-ExamplesAddingMQTTDevice.md
- docs_src/examples/Ch-ExamplesAddingModbusDevice.md
- docs_src/getting-started/Ch-GettingStartedSDK-C.md
- docs_src/getting-started/Ch-GettingStartedSDK-Go.md
- docs_src/getting-started/Ch-GettingStartedUsersNexus.md
- docs_src/getting-started/quick-start/index.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/deployment.md
- docs_src/security/Ch-RemoteDeviceServices.md
> refactor: [main] Replace use of docker-compose command with docker compose CLI command

- docs_src/microservices/device/supported/device-onvif-camera/General.md
- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/custom-build.md
- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/deployment.md
- docs_src/microservices/device/supported/device-usb-camera/General.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/custom-build.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/deployment.md
> refactor: add version macro and some cleanups for onvif and usb docs

- docs_src/microservices/device/supported/device-onvif-camera/General.md
- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/custom-build.md
- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/deployment.md
- docs_src/microservices/device/supported/device-usb-camera/General.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/custom-build.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/deployment.md
> refactor: Clean up and addition of version macro to clone the repo based on the release version

- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/general-usage.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/general-usage.md
> feat: added troubleshooting info for axis onvif camera issue

- docs_src/microservices/device/supported/device-usb-camera/walkthrough/deployment.md
> fix: add cardName and serialNumber related docs to address panic error

- docs_src/microservices/application/ApplicationServiceAPI.md
> feat: [APP SDK] Document new AppContext API

- docs_src/microservices/support/scheduler/Ch-Scheduler.md
corresponding change of edgexfoundry/edgex-go#4594
Signed-off-by: Jack Chen <jack@iotechsys.com>
> fix: Initialize interval in the local time zone

- docs_src/microservices/application/BuiltIn.md
> feat: Add note about filtering using regexp

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
> fix: Address PR comments for filtering feature

- docs_src/microservices/application/ApplicationServiceAPI.md
> fix: [Napa] Remove notes about not valid with HTTP/External-MQTT trigger

- docs_src/microservices/application/ApplicationServiceAPI.md
> fix: [Minnesota] Remove notes about not valid with HTTP/External-MQTT trigger

- docs_src/V3TopLevelMigration.md
- docs_src/microservices/device/V3Migration.md
close #1126 
**Once this is merged, will make the same changes on minnesota branch.
> fix: Add device properties addition and notify removal

- docs_src/V3TopLevelMigration.md
- docs_src/microservices/device/V3Migration.md
> fix: [Minnesota] Add device properties addition and notify removal

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/ApplicationServiceAPI.md
- docs_src/microservices/device/sdk/SDK-Go-API.md
> fix(security): Deprecate AddRoute which adds unauthenticated custom routes

- docs_src/microservices/core/metadata/Ch-Metadata.md
> fix:[main] update data dictionary for missing tab description

- docs_src/microservices/core/metadata/Ch-Metadata.md
> fix: [minnesota] update data dictionary for missing tab description

- docs_src/getting-started/Ch-GettingStartedHybrid.md
> fix: [minnesota] Add -o flag on a hybrid mode

- docs_src/getting-started/Ch-GettingStartedHybrid.md
> fix: [main] Add -o flag on a hybrid mode

- docs_src/examples/app-service-examples/camera-management/Ch-CameraManagement.md
- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/deployment.md
- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/general-usage.md
- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/setup.md
- docs_src/microservices/device/supported/device-onvif-camera/supplementary-info/test-with-postman.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/deployment.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/general-usage.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/setup.md
> fix: updates and fixes per validation feedback

- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/ApplicationServiceAPI.md
> fix: Add documentation for Publish and PublishWIthTopic

- docs_src/microservices/device/sdk/SDK-Go-API.md
Modify handler param of AddCustomRoute to use the signature of echo.HandlerFunc.
> fix: Modify handler param of AddCustomRoute

- docs_src/microservices/device/V3Migration.md
> fix: Add note for v3 ResourceProperty `mask`

- docs_src/examples/Ch-ExamplesAddingModbusDevice.md
- docs_src/examples/Ch-ExamplesModbusdatatypeconversion.md
Those changes are linked to the PR (https://github.com/edgexfoundry/device-modbus-go/pull/492), more details can be found there.
> feat: rawType int32 added for modbus ds

- docs_src/microservices/device/supported/device-onvif-camera/Walkthrough/setup.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/setup.md
> feat: Add information to run via proxy for usb/onvif services

- docs_src/microservices/application/AppServiceConfigurable.md
- docs_src/microservices/application/BuiltIn.md
> feat: update details for http request headers

- docs_src/security/Ch-CORS-Settings.md
> fix: Updated CORS configuration instructions for API gateway

- docs_src/examples/app-service-examples/camera-management/Ch-CameraManagement.md
- docs_src/microservices/device/supported/device-usb-camera/supplementary-info/advanced-options.md
- docs_src/microservices/device/supported/device-usb-camera/walkthrough/custom-build.md
> fix: Update RTSP server configuration

- docs_src/microservices/device/Ch-DeviceServiceList.md
> fix: update DeviceServiceList

- docs_src/security/Ch-CORS-Settings.md
> fix: update CORES docs for individual service

- docs_src/microservices/core/metadata/Ch-Metadata.md
> docs: Add URI for File information to UoM docs

- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/general/index.md
> docs: Add uri for file information for config files

- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/core/metadata/Ch-Metadata.md
- docs_src/microservices/device/Ch-DeviceServices.md
> docs: Add URI for Files Device info

- docs_src/microservices/device/supported/device-usb-camera/supplementary-info/advanced-options.md
> docs: Add docs for pixelFormat command and some cleanup of old commands.

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/ApplicationServiceAPI.md
> docs: Update appservice AddCustomRoute to match echo

- docs_src/microservices/application/available/AppRecordReplay.md
> feat: Document new App Record Replay service

- docs_src/microservices/core/data/Ch-CoreData.md
Add data retention config for controlling the events and readings retention feature
> docs: Add data retention config

- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
> feat: Document new -rsh/--remoteServiceHosts flag and env override

- docs_src/microservices/support/notifications/Ch-AlertsNotifications.md
Add notification retention config for controlling the notifications retention feature
> docs: Add notification retention config

- docs_src/microservices/configuration/CommonCommandLineOptions.md
> feat: Add security warning to new Remote Service Hosts flag

- docs_src/microservices/application/AdvancedTopics.md
Adds deprecation notice to advanced topics page with link to newly added alternatives.  Fixes #1223.
> docs: Note Background Publisher Deprecation in Advanced Topics

- docs_src/microservices/general/messagebus.md
> refactor: More refinement of MessageBus doc

- docs_src/microservices/device/Ch-DeviceServices.md
> docs: Update provision URI for Files description for profiles and provision watchers

- docs_src/V3TopLevelMigration.md
> fix: [main] Correct link to Device File migration

- docs_src/V3TopLevelMigration.md
> fix: [minnesota] Correct link to Device File migration

- docs_src/microservices/application/AppFunctionContextAPI.md
- docs_src/microservices/application/ApplicationServiceAPI.md
> feat: Document new ReadingClient APIs

- docs_src/microservices/configuration/CommonCommandLineOptions.md
This option is also useful in secure-mode when deploying service remotely
> fix: Correct link to env and remove warning

- docs/versions.json
> refactor: Remove Fuji and reverse order in version in Drop Down

- docs_src/examples/Ch-ExamplesDataandRetention.md
- mkdocs.yml
> feat: add core-data retentation docs

- docs_src/microservices/application/AdvancedTopics.md
- docs_src/microservices/application/GeneralAppServiceConfig.md
> feat: Document new app service export error metrics

- docs_src/microservices/device/services/device-usb-camera/walkthrough/custom-build.md
> docs: add docs for RtspServerMode configuration

- docs_src/microservices/device/remote/Ch-RemoteNonSecure.md
> docs: small changes to the non secure remote deployment device docs

- docs_src/microservices/device/services/device-onvif-camera/supplementary-info/ONVIF-protocol.md
> fix: Fix link causing doc builds to fail

- docs_src/api/core/Ch-APICoreData.md
- docs_src/microservices/application/V3Migration.md
- docs_src/microservices/application/services/AppLLRPInventory.md
- docs_src/microservices/application/services/AppRecordReplay/ApiReference.md
- docs_src/microservices/application/services/AppRecordReplay/Configuration.md
- docs_src/microservices/application/services/AppRecordReplay/GettingStarted.md
- docs_src/microservices/application/services/AppRecordReplay/Purpose.md
- docs_src/microservices/application/services/AppRecordReplay/SourceCode.md
- docs_src/microservices/application/services/AppServiceConfigurable/ApiReference.md
- docs_src/microservices/application/services/AppServiceConfigurable/Configuration.md
- docs_src/microservices/application/services/AppServiceConfigurable/GettingStarted.md
- docs_src/microservices/application/services/AppServiceConfigurable/Purpose.md
- docs_src/microservices/application/services/AppServiceConfigurable/SourceCode.md
- docs_src/microservices/application/services/AppServiceConfigurable/details/AvailablePipelineFunctions.md
- docs_src/microservices/application/services/AppServiceConfigurable/details/PipelinePerTopics.md
- docs_src/microservices/application/services/AppServiceConfigurable/details/Profiles.md
- docs_src/microservices/application/services/AppServiceConfigurable/details/TargetType.md
- docs_src/microservices/core/data/ApiReference.md
- docs_src/microservices/core/data/Configuration.md
- docs_src/microservices/core/data/GettingStarted.md
- docs_src/microservices/core/data/Purpose.md
- docs_src/microservices/core/data/SourceCode.md
- docs_src/microservices/core/data/details/EventsAndReadings.md
- mkdocs.yml
combine top and page heading into top heading
Add title override for Web Browser page title
> refactor: Rework page titles

- docs_src/microservices/application/sdk/api/BuiltInPipelineFunctions.md
- docs_src/microservices/application/sdk/details/Triggers.md
- docs_src/microservices/application/services/AppServiceConfigurable/details/AvailablePipelineFunctions.md
> feat: Add MQTT Will options documentation

- docs_src/microservices/device/services/device-onvif-camera/supplementary-info/ONVIF-protocol.md
> fix: Replace broken link to DS-2DE2A404IW-DE3S6 camera spec

- docs_src/microservices/application/Configuration.md
> refactor:[App Services] Tweaks for flagging restarted needs and pulled from common config

- docs_src/microservices/core/data/GettingStarted.md
- docs_src/microservices/support/scheduler/GettingStarted.md
> fix: Address feedback on support scheduler refactor

- docs_src/threat-models/secret-store/background.md
> fix: Remove dead google docs link

- docs_src/microservices/device/services/device-mqtt/SourceCode.md
- docs_src/microservices/device/services/device-uart.md
- docs_src/microservices/device/services/device-uart/APIReference.md
- docs_src/microservices/device/services/device-uart/Configuration.md
- docs_src/microservices/device/services/device-uart/GettingStarted.md
- docs_src/microservices/device/services/device-uart/Purpose.md
- docs_src/microservices/device/services/device-uart/SourceCode.md
- mkdocs.yml
> feat: Add device UART docs, fix link in device mqtt

- docs_src/microservices/device/services/device-rest/ProtocolProperties.md
- mkdocs.yml
> feat: Document Device REST's Protocol Properties

- docs_src/microservices/device/services/device-gpio.md
- docs_src/microservices/device/services/device-gpio/ApiReference.md
- docs_src/microservices/device/services/device-gpio/Configuration.md
- docs_src/microservices/device/services/device-gpio/GettingStarted.md
- docs_src/microservices/device/services/device-gpio/ProtocolProperties.md
- docs_src/microservices/device/services/device-gpio/Purpose.md
- docs_src/microservices/device/services/device-gpio/SourceCode.md
- mkdocs.yml
> refactor: Rework Device GPIO docs into new 3.1 structure

- docs_src/microservices/device/services/device-uart/ProtocolProperties.md
- mkdocs.yml
> feat: Document Device UART Protocol Properties

- docs_src/microservices/device/services/device-mqtt/ProtocolProperties.md
- docs_src/microservices/device/services/device-rest/ProtocolProperties.md
- mkdocs.yml
> feat: Document Device MQTT protocol properties

- docs_src/microservices/device/details/DeviceProfiles.md
> feat: Add Device Service Device Profile documentation

- docs_src/microservices/device/sdk/api/GoDeviceSDK/GoProtocolDriverAPI.md
> feat: Add ProtocolDrive documentation

- docs_src/examples/index.md
> fix: Helm link broken

- docs/versions.json
- template_macros.yaml
> fix: automated release changes

- mkdocs.yml
> ci: update mkdocs.yml to 3.2

- docs/versions.json
> ci: update odessa version number in versions.json

- docs_src/examples/app-service-examples/camera-management/Ch-CameraManagement.md
- docs_src/microservices/device/services/device-usb-camera/supplementary-info/advanced-options.md
- docs_src/microservices/device/services/device-usb-camera/walkthrough/custom-build.md
> fix: [napa] Update configuration for enabling RTSP server 

- docs_src/examples/app-service-examples/camera-management/Ch-CameraManagement.md
- docs_src/microservices/device/services/device-usb-camera/supplementary-info/advanced-options.md
- docs_src/microservices/device/services/device-usb-camera/walkthrough/custom-build.md
> fix: Update configuration for enabling RTSP Server 

- docs_src/examples/app-service-examples/camera-management/Ch-CameraManagement.md
> fix: Add rtsp server executable config to env var

- docs_src/design/TOC.md
- docs_src/microservices/application/sdk/api/BuiltInPipelineFunctions.md
- docs_src/microservices/application/services/AppServiceConfigurable/details/AvailablePipelineFunctions.md
> feat: Document new MQTT Export Pre-connect capability

- docs_src/microservices/application/sdk/api/AppFunctionContextAPI.md
> fix: Correct typos

- docs_src/general/ServicePorts.md
Resolves #1340. Add device-s7 service port.
> feat: Add device-s7 service port

- docs_src/microservices/application/sdk/api/BuiltInPipelineFunctions.md
> feat: Add SetOnConnectHandler in BuiltInPipelinsFuncions

- docs_src/V3TopLevelMigration.md
- docs_src/api/core/Ch-APICoreCommand.md
- docs_src/design/adr/0026-Common Configuration.md
- docs_src/design/adr/013-Device-Service-Events-Message-Bus.md
- docs_src/getting-started/Ch-GettingStartedHybrid.md
- docs_src/index.md
- docs_src/microservices/application/sdk/api/AppFunctionContextAPI.md
- docs_src/microservices/application/sdk/api/ApplicationServiceAPI.md
- docs_src/microservices/application/sdk/api/BuiltInPipelineFunctions.md
- docs_src/microservices/application/services/AppRecordReplay/GettingStarted.md
- docs_src/microservices/application/services/AppServiceConfigurable/details/Profiles.md
- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/core/command/Configuration.md
- docs_src/microservices/core/command/GettingStarted.md
- docs_src/microservices/device/Configuration.md
- docs_src/microservices/device/V3Migration.md
- docs_src/microservices/device/sdk/api/GoDeviceSDK/GoDeviceSDKAPI.md
- docs_src/microservices/device/sdk/details/CustomServiceMetrics.md
- docs_src/microservices/device/sdk/details/Secrets.md
- docs_src/microservices/device/sdk/devicesdk-getting-started/GettingStartedSDK-Go.md
- docs_src/microservices/device/services/device-mqtt.md
- docs_src/microservices/device/services/device-onvif-camera/Walkthrough/custom-build.md
- docs_src/microservices/device/services/device-onvif-camera/supplementary-info/test-with-postman.md
- docs_src/microservices/general/index.md
- docs_src/microservices/general/messagebus.md
- docs_src/walk-through/Ch-WalkthroughReading.md
- mkdocs.yml
> fix: Jenkins build error

- docs_src/api/core/Ch-APICoreConfigurationAndRegistry.md
- docs_src/api/core/Ch-APICoreKeeper.md
- docs_src/api/support/Ch-APISupportCronScheduler.md
- docs_src/microservices/configuration/ConfigurationAndRegistry.md
- mkdocs.yml
> feat: Add API documents for Core Keeper and Support Cron Scheduler

- docs_src/microservices/core/metadata/details/DeviceSystemEvents.md
- docs_src/microservices/general/index.md
> feat: added Timestamp precision

- docs_src/microservices/support/cronScheduler/GettingStarted.md
> feat: Update docs for auto triggering scheduled jobs

- docs_src/microservices/general/database/Ch-Postgres.md
- docs_src/microservices/general/database/Ch-Redis.md
- docs_src/microservices/support/cronScheduler/GettingStarted.md
- mkdocs.yml
Resolves #1375. Add docs for PostgreSQL db usage in EdgeX.
> feat: Add docs for PostgreSQL db usage in EdgeX

- docs_src/microservices/support/cronScheduler/Configuration.md
- docs_src/microservices/support/cronScheduler/details/DataRetention.md
- mkdocs.yml
refer to https://github.com/edgexfoundry/edgex-go/issues/4912
> feat: Add support-cron-scheduler retention docs

- docs_src/api/core/Ch-APICoreConfigurationAndRegistry.md
- docs_src/microservices/application/sdk/api/BuiltInPipelineFunctions.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
- docs_src/microservices/configuration/ConfigurationAndRegistry.md
- docs_src/microservices/device/sdk/DeviceSystemEvents.md
- docs_src/microservices/support/cronScheduler/Configuration.md
- docs_src/microservices/support/scheduler/GettingStarted.md
- mkdocs.yml
> fix: Replace release version 3.2 with 4.0

- docs_src/api/core/Ch-APICoredata.md
- mkdocs.yml
> fix: correct the title of Core-data API docs

- docs_src/microservices/support/cronScheduler/ApiReference.md
- docs_src/microservices/support/cronScheduler/GettingStarted.md
> fix: update api and db links

- docs_src/microservices/device/details/AutoEvents.md
Add AutoEvent onChangeThreshold usage
> feat: Add AutoEvent onChangeThreshold usage

- docs_src/microservices/general/messagebus.md
> fix: remove redis pub/sub on msg bus page

- docs_src/api/core/Ch-APICoreConfigurationAndRegistry.md
- docs_src/getting-started/Ch-GettingStartedDockerUsers.md
- docs_src/getting-started/native/Ch-BuildRunOnArm32.md
- docs_src/getting-started/native/Ch-BuildRunOnLinuxDistro.md
- docs_src/getting-started/native/Ch-BuildRunOnWindows.md
- docs_src/microservices/application/Configuration.md
- docs_src/microservices/configuration/CommonCommandLineOptions.md
- docs_src/microservices/configuration/CommonConfiguration.md
- docs_src/microservices/configuration/CommonEnvironmentVariables.md
- docs_src/microservices/configuration/ConfigurationAndRegistry.md
- docs_src/microservices/core/data/details/DataRetention.md
- docs_src/microservices/device/services/device-onvif-camera/Walkthrough/deployment.md
- docs_src/microservices/device/services/device-onvif-camera/supplementary-info/auto-discovery.md
- docs_src/microservices/device/services/device-onvif-camera/supplementary-info/getting-started-with-docker-security.md
- docs_src/microservices/device/services/device-onvif-camera/supplementary-info/utility-scripts.md
> fix: replace consul with core-keeper

- docs_src/microservices/general/messagebus.md
> fix: refine the statement of msg bus on napa branch

- docs_src/microservices/support/scheduler/GettingStarted.md
- docs_src/microservices/support/scheduler/Purpose.md
> fix: update support scheduler service docs

- docs_src/microservices/general/database/Ch-Postgres.md
fix https://github.com/edgexfoundry/edgex-docs/issues/1416
> feat: add docs for PostgreSQL table schema migration

- docs_src/microservices/core/data/Configuration.md
- docs_src/microservices/core/data/details/DataRetention.md
Update Event Retention doc to introduce the enhancement.
> feat: Update Event Retention doc

- docs_src/microservices/core/data/details/DataRetention.md
> fix: add more use cased and note on core data retention docs

- docs_src/microservices/core/command/GettingStarted.md
- docs_src/microservices/device/services/device-onvif-camera/General.md
- docs_src/microservices/device/services/device-usb-camera/General.md
> fix: Update Core Command docs for payload change

- docs_src/microservices/core/command/GettingStarted.md
- docs_src/microservices/device/sdk/DeviceSystemEvents.md
- docs_src/microservices/general/messagebus.md
relate: https://github.com/edgexfoundry/go-mod-messaging/issues/381
> feat: add message envelope change note

- docs_src/microservices/application/sdk-python/GettingStarted.md
- docs_src/microservices/application/sdk-python/Purpose.md
- docs_src/microservices/application/sdk-python/SourceCode.md
- docs_src/microservices/application/sdk-python/api/AppFunctionContextAPI.md
- docs_src/microservices/application/sdk-python/api/ApplicationServiceAPI.md
- docs_src/microservices/application/sdk-python/api/BuiltInPipelineFunctions.md
- docs_src/microservices/application/sdk-python/details/CustomConfiguration.md
- docs_src/microservices/application/sdk-python/details/CustomRestApis.md
- docs_src/microservices/application/sdk-python/details/CustomServiceMetrics.md
- docs_src/microservices/application/sdk-python/details/ErrorHandling.md
- docs_src/microservices/application/sdk-python/details/PipelinesPerTopics.md
- docs_src/microservices/application/sdk-python/details/PublishingMessageBus.md
- docs_src/microservices/application/sdk-python/details/Secrets.md
- docs_src/microservices/application/sdk-python/details/StoreAndForward.md
- docs_src/microservices/application/sdk-python/details/TargetType.md
- mkdocs.yml
We have publish the new app-functions-sdk-python, so adding corresponding documentation.
> feat: add app-functions-sdk-python documentation

- docs_src/examples/Ch-ExamplesVirtualDeviceService.md
- docs_src/getting-started/quick-start/index.md
- docs_src/microservices/application/sdk-python/GettingStarted.md
- docs_src/microservices/application/sdk/GettingStarted.md
- docs_src/microservices/application/services/AppLLRPInventory/details/InventoryEvents.md
- docs_src/microservices/core/command/details/RegexGetCommand.md
- docs_src/microservices/device/services/device-gpio/GettingStarted.md
- docs_src/microservices/device/services/device-onvif-camera/supplementary-info/friendlyname-mac.md
- docs_src/microservices/device/services/device-opc-ua/GettingStarted.md
- docs_src/microservices/device/services/device-s7/GettingStarted.md
- docs_src/microservices/device/services/device-usb-camera/supplementary-info/advanced-options.md
- docs_src/walk-through/Ch-WalkthroughReading.md
Since the reading schema changed, remove id from the reading.
> feat: Update Event Reading example

- docs/versions.json
- mkdocs.yml
updated version for the main branch
4.0 > 4.1
> ci: update docs version for the main branch

- docs/versions.json
> fix: update Odessa to Odesa

- mkdocs.yml
> fix: typo on device-opc-ua mkdocs file

- docs_src/microservices/general/index.md
> feat: Added new section for reserved character

- docs_src/microservices/general/index.md
> feat: Added new section for reserved character on odesa branch

- docs_src/getting-started/quick-start/index.md
> fix: remove consul dependency and add env to override broker clientid

- docs_src/api/Ch-APIIntroduction.md
> fix: typo on api intro

- docs_src/microservices/general/index.md
Add example for NameFieldEscape config.
> feat: Add NameFieldEscape config doc

- docs_src/security/Ch-Configuring-Add-On-Services.md
> fix: remove redisDB and consul on 4.0

- docs_src/microservices/general/database/Ch-Postgres.md
Resolves #1470. Modify PostgreSQL doc to add the EdgeX service list using the db.
> fix: Modify PostgreSQL doc to add the service list using the db

- docs_src/design/TOC.md
- docs_src/design/adr/0031-Reduce-Payload-Size-For-Device-Events.md
> feat: reduce device event payload size ADR

- docs_src/microservices/general/messagebus.md
Add EDGEX_OPTIMIZE_EVENT_PAYLOAD env variable for reducing the event payload, refer to the ADR https://docs.edgexfoundry.org/4.1/design/adr/0031-Reduce-Payload-Size-For-Device-Events/.
> feat: Update MessageBus doc for event payload optimization
